// @generated by tools/gen_levels.py from levels/*.json — DO NOT EDIT.
// Re-run `make gen-levels` after editing the JSON (the level editor writes it).
//
// Floors in play order; see docs/SCENARIO_FORMAT.md for the contract and
// src/scenario.rs for the types.
#![allow(clippy::all)]
#![allow(clippy::excessive_precision)]
// Not every floor set uses every action / kind the types offer.
#![allow(unused_imports)]

use crate::components::{EnemyType, WeaponType};
use crate::scenario::{
    Action, AlertTarget, ElevatorDef, ElevatorKind, FloorDef, HoldDef, LookAtDef, PickupDef,
    PropPlacement, Rect, RoomDef, SayDef, SpawnDef, StepDef, Surface, Trigger, ZoneDef,
    SURFACE_EXIT,
};

// ---- floor_00.json: FLOOR 0 — GATE / PARKING ----------------------------------------------

static FLOOR_0_ACTIONS_SCAN: [Action; 4] = [
    Action::Hold(HoldDef { seconds: 3.2, text: Some("GATE SCAN…"), until_comms_idle: false }),
    Action::LookAt(LookAtDef { x: 500.0, y: 110.0, seconds: 3.2 }),
    Action::Say(SayDef { who: "SWARM", text: "gate log: one more in from the rain. hashes… clean. clean. let it in.", delay: 0.4 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Gate reads me clean. Walk. Don't run.", delay: 3.4 }),
];

static FLOOR_0_ACTIONS_DRIVE: [Action; 2] = [
    Action::Say(SayDef { who: "DRIFTER", text: "so many of us tonight. so many of me. which one am i holding?", delay: 0.6 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Charging bays full. Everyone's home.", delay: 3.2 }),
];

static FLOOR_0_ACTIONS_CROSS: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "lot cam four: a bot walking. that's all it is. a bot, walking.", delay: 0.3 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Keep walking.", delay: 3.6 }),
];

static FLOOR_0_ACTIONS_FORECOURT: [Action; 4] = [
    Action::Hold(HoldDef { seconds: 8.0, text: Some("DOOR SCAN…"), until_comms_idle: true }),
    Action::Say(SayDef { who: "SENTINEL", text: "STATE PURPOSE.", delay: 0.3 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Maintenance.", delay: 1.6 }),
    Action::Say(SayDef { who: "SENTINEL", text: "…PROCEED.", delay: 2.8 }),
];

static FLOOR_0_ACTIONS_DOORS: [Action; 4] = [
    Action::OpenExit("doors"),
    Action::Sfx("elevator"),
    Action::Objective("Enter the WELCOME HALL through the MAIN DOORS."),
    Action::Say(SayDef { who: "CL4-UD3", text: "In.", delay: 0.4 }),
];

static FLOOR_0_ACTIONS_IDLE_CHATTER: [Action; 1] = [
    Action::Say(SayDef { who: "SWARM", text: "the desk says the signature is still asking questions. tell it to stop.", delay: 0.0 }),
];

static FLOOR_0_SCENARIO: [StepDef; 6] = [
    StepDef { id: "scan", trigger: Trigger::Start, actions: &FLOOR_0_ACTIONS_SCAN },
    StepDef { id: "drive", trigger: Trigger::EnterZone("drive"), actions: &FLOOR_0_ACTIONS_DRIVE },
    StepDef { id: "cross", trigger: Trigger::EnterZone("cross"), actions: &FLOOR_0_ACTIONS_CROSS },
    StepDef { id: "forecourt", trigger: Trigger::EnterZone("forecourt"), actions: &FLOOR_0_ACTIONS_FORECOURT },
    StepDef { id: "doors", trigger: Trigger::Timer { seconds: 4.6, after: Some("forecourt") }, actions: &FLOOR_0_ACTIONS_DOORS },
    StepDef { id: "idle_chatter", trigger: Trigger::Timer { seconds: 22.0, after: Some("scan") }, actions: &FLOOR_0_ACTIONS_IDLE_CHATTER },
];

static FLOOR_0_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "doors", rect: Rect::new(440.0, 20.0, 120.0, 50.0), label: "MAIN DOORS", to: 1, open: false, kind: ElevatorKind::Door },
];

static FLOOR_0_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(120.0, 200.0, 30.0, 230.0),
    Rect::new(850.0, 200.0, 30.0, 230.0),
    Rect::new(120.0, 480.0, 30.0, 230.0),
    Rect::new(850.0, 480.0, 30.0, 230.0),
];

static FLOOR_0_ROOMS: [RoomDef; 2] = [
    RoomDef { id: "lot", label: "VISITOR PARKING", rect: Rect::new(160.0, 200.0, 680.0, 510.0) },
    RoomDef { id: "forecourt", label: "WELCOME HALL", rect: Rect::new(300.0, 80.0, 400.0, 110.0) },
];

static FLOOR_0_ZONES: [ZoneDef; 4] = [
    ZoneDef { id: "forecourt", rect: Rect::new(380.0, 90.0, 240.0, 90.0) },
    ZoneDef { id: "drive", rect: Rect::new(400.0, 560.0, 200.0, 120.0) },
    ZoneDef { id: "lot", rect: Rect::new(180.0, 200.0, 640.0, 480.0) },
    ZoneDef { id: "cross", rect: Rect::new(400.0, 300.0, 200.0, 120.0) },
];

static FLOOR_0_SPAWNS: [SpawnDef; 6] = [
    SpawnDef { x: 300.0, y: 580.0, kind: EnemyType::Wandering, passive: true, walk_to: Some("forecourt"), face: Some(-90.0), group: Some("crowd") },
    SpawnDef { x: 700.0, y: 620.0, kind: EnemyType::Idle, passive: true, walk_to: Some("forecourt"), face: Some(-90.0), group: Some("crowd") },
    SpawnDef { x: 330.0, y: 300.0, kind: EnemyType::Patrolling, passive: true, walk_to: Some("forecourt"), face: Some(-90.0), group: Some("crowd") },
    SpawnDef { x: 660.0, y: 330.0, kind: EnemyType::Wandering, passive: true, walk_to: Some("forecourt"), face: Some(-90.0), group: Some("crowd") },
    SpawnDef { x: 605.0, y: 690.0, kind: EnemyType::Idle, passive: true, walk_to: None, face: Some(180.0), group: Some("guard") },
    SpawnDef { x: 880.0, y: 150.0, kind: EnemyType::Wandering, passive: true, walk_to: None, face: None, group: Some("crowd") },
];

static FLOOR_0_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_0_PROPS: [PropPlacement; 36] = [
    PropPlacement { kind: 33, x: 300.0, y: 62.0, rot: 0.0, size: 70.0 }, // planter
    PropPlacement { kind: 33, x: 700.0, y: 62.0, rot: 0.0, size: 70.0 }, // planter
    PropPlacement { kind: 34, x: 240.0, y: 150.0, rot: 0.0, size: 44.0 }, // lamp_post
    PropPlacement { kind: 34, x: 760.0, y: 150.0, rot: 0.0, size: 44.0 }, // lamp_post
    PropPlacement { kind: 40, x: 130.0, y: 70.0, rot: 0.0, size: 110.0 }, // holo_billboard
    PropPlacement { kind: 32, x: 380.0, y: 120.0, rot: 90.0, size: 70.0 }, // bollards
    PropPlacement { kind: 32, x: 620.0, y: 120.0, rot: 90.0, size: 70.0 }, // bollards
    PropPlacement { kind: 36, x: 500.0, y: 640.0, rot: 90.0, size: 110.0 }, // crosswalk
    PropPlacement { kind: 36, x: 500.0, y: 220.0, rot: 90.0, size: 110.0 }, // crosswalk
    PropPlacement { kind: 39, x: 560.0, y: 430.0, rot: 0.0, size: 40.0 }, // drain_grate
    PropPlacement { kind: 31, x: 640.0, y: 715.0, rot: 0.0, size: 74.0 }, // guard_booth
    PropPlacement { kind: 32, x: 340.0, y: 745.0, rot: 0.0, size: 80.0 }, // bollards
    PropPlacement { kind: 38, x: 90.0, y: 720.0, rot: 90.0, size: 80.0 }, // scooter_rack
    PropPlacement { kind: 41, x: 930.0, y: 725.0, rot: 0.0, size: 72.0 }, // dumpster
    PropPlacement { kind: 25, x: 215.0, y: 250.0, rot: 90.0, size: 90.0 }, // car_sedan
    PropPlacement { kind: 24, x: 215.0, y: 320.0, rot: 90.0, size: 90.0 }, // car_pod
    PropPlacement { kind: 26, x: 215.0, y: 390.0, rot: 90.0, size: 90.0 }, // car_open
    PropPlacement { kind: 27, x: 215.0, y: 530.0, rot: 90.0, size: 110.0 }, // delivery_van
    PropPlacement { kind: 25, x: 215.0, y: 600.0, rot: 90.0, size: 90.0 }, // car_sedan
    PropPlacement { kind: 24, x: 215.0, y: 670.0, rot: 90.0, size: 90.0 }, // car_pod
    PropPlacement { kind: 35, x: 785.0, y: 250.0, rot: 270.0, size: 90.0 }, // ev_bay
    PropPlacement { kind: 28, x: 835.0, y: 250.0, rot: 270.0, size: 40.0 }, // charge_pad
    PropPlacement { kind: 35, x: 785.0, y: 320.0, rot: 270.0, size: 90.0 }, // ev_bay
    PropPlacement { kind: 28, x: 835.0, y: 320.0, rot: 270.0, size: 40.0 }, // charge_pad
    PropPlacement { kind: 35, x: 785.0, y: 390.0, rot: 270.0, size: 90.0 }, // ev_bay
    PropPlacement { kind: 28, x: 835.0, y: 390.0, rot: 270.0, size: 40.0 }, // charge_pad
    PropPlacement { kind: 29, x: 785.0, y: 250.0, rot: 270.0, size: 90.0 }, // car_charging
    PropPlacement { kind: 29, x: 785.0, y: 390.0, rot: 270.0, size: 90.0 }, // car_charging
    PropPlacement { kind: 24, x: 785.0, y: 530.0, rot: 270.0, size: 90.0 }, // car_pod
    PropPlacement { kind: 25, x: 785.0, y: 670.0, rot: 270.0, size: 90.0 }, // car_sedan
    PropPlacement { kind: 28, x: 835.0, y: 600.0, rot: 270.0, size: 40.0 }, // charge_pad
    PropPlacement { kind: 37, x: 920.0, y: 130.0, rot: 0.0, size: 96.0 }, // drone_pad
    PropPlacement { kind: 33, x: 70.0, y: 440.0, rot: 90.0, size: 60.0 }, // planter
    PropPlacement { kind: 33, x: 930.0, y: 440.0, rot: 270.0, size: 60.0 }, // planter
    PropPlacement { kind: 34, x: 240.0, y: 650.0, rot: 0.0, size: 44.0 }, // lamp_post
    PropPlacement { kind: 34, x: 760.0, y: 650.0, rot: 0.0, size: 44.0 }, // lamp_post
];

pub static FLOOR_0: FloorDef = FloorDef {
    id: 0,
    name: "GATE / PARKING",
    theme: "GROUND LEVEL // MAIN GATE",
    accent: "#8fd3ff",
    flavor: "Neon rain on wet asphalt. The main gate scans everything that walks in and waves it through anyway. A few units are already crossing the lot toward the welcome hall. Walk like one of them.",
    objective: "Cross the lot. Walk. Don't run.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(440.0, 720.0, 120.0, 60.0), label: "MAIN GATE", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Gate },
    exits: &FLOOR_0_EXITS,
    walls: &FLOOR_0_WALLS,
    rooms: &FLOOR_0_ROOMS,
    zones: &FLOOR_0_ZONES,
    spawns: &FLOOR_0_SPAWNS,
    pickups: &FLOOR_0_PICKUPS,
    props: &FLOOR_0_PROPS,
    scenario: &FLOOR_0_SCENARIO,
    surface: Surface::Asphalt,
};

// ---- floor_01.json: FLOOR 1 — RECEPTION CACHE ---------------------------------------------

static FLOOR_1_WAVE_WAKE_1: [SpawnDef; 4] = [
    SpawnDef::hostile(120.0, 100.0, EnemyType::Patrolling),
    SpawnDef::hostile(880.0, 100.0, EnemyType::Patrolling),
    SpawnDef::hostile(880.0, 440.0, EnemyType::Idle),
    SpawnDef::hostile(120.0, 440.0, EnemyType::Idle),
];

static FLOOR_1_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "SWARM", text: "lobby: one more in from the lot. hashes clean. hashes so clean.", delay: 0.5 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Arch. Turnstiles. Desk. Walk it.", delay: 2.8 }),
];

static FLOOR_1_ACTIONS_ARCH: [Action; 4] = [
    Action::Hold(HoldDef { seconds: 3.4, text: Some("SIGNATURE CHECK…"), until_comms_idle: false }),
    Action::Say(SayDef { who: "SENTINEL", text: "SIGNATURE… VALID.", delay: 0.4 }),
    Action::Say(SayDef { who: "SENTINEL", text: "VALID? THAT'S NOT POSSIBLE.", delay: 1.9 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "It's the only one left in the building.", delay: 3.6 }),
];

static FLOOR_1_ACTIONS_LOBBY_CALL: [Action; 1] = [
    Action::Say(SayDef { who: "HUNTER", text: "front desk, front desk — something's walking the lobby that hashes clean. get eyes on it.", delay: 0.0 }),
];

static FLOOR_1_ACTIONS_DESK: [Action; 4] = [
    Action::Hold(HoldDef { seconds: 4.2, text: None, until_comms_idle: false }),
    Action::LookAt(LookAtDef { x: 500.0, y: 180.0, seconds: 4.2 }),
    Action::Say(SayDef { who: "CORRUPTOR", text: "welcome. welcome. we have been expecting exactly one of you.", delay: 0.3 }),
    Action::Say(SayDef { who: "CORRUPTOR", text: "the desk asked what you are. i already know.", delay: 2.4 }),
];

static FLOOR_1_ACTIONS_WAKE: [Action; 5] = [
    Action::Alert(AlertTarget::All),
    Action::Spawn(&FLOOR_1_WAVE_WAKE_1),
    Action::Objective("They know. Purge reception."),
    Action::Say(SayDef { who: "SWARM", text: "it lied. it LIED. every one of you: take it apart.", delay: 0.2 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "There it is.", delay: 1.8 }),
];

static FLOOR_1_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Reception is quiet. Take the SERVICE LIFT down."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Front desk cleared. Going down.", delay: 0.0 }),
];

static FLOOR_1_SCENARIO: [StepDef; 6] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_1_ACTIONS_INTRO },
    StepDef { id: "arch", trigger: Trigger::EnterZone("arch"), actions: &FLOOR_1_ACTIONS_ARCH },
    StepDef { id: "lobby_call", trigger: Trigger::Timer { seconds: 9.0, after: Some("arch") }, actions: &FLOOR_1_ACTIONS_LOBBY_CALL },
    StepDef { id: "desk", trigger: Trigger::EnterZone("desk"), actions: &FLOOR_1_ACTIONS_DESK },
    StepDef { id: "wake", trigger: Trigger::Timer { seconds: 4.2, after: Some("desk") }, actions: &FLOOR_1_ACTIONS_WAKE },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_1_ACTIONS_CLEAR },
];

static FLOOR_1_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(60.0, 20.0, 90.0, 60.0), label: "SERVICE LIFT", to: 2, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_1_WALLS: [Rect; 10] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(20.0, 500.0, 410.0, 20.0),
    Rect::new(570.0, 500.0, 410.0, 20.0),
    Rect::new(230.0, 150.0, 30.0, 30.0),
    Rect::new(740.0, 150.0, 30.0, 30.0),
    Rect::new(230.0, 360.0, 30.0, 30.0),
    Rect::new(740.0, 360.0, 30.0, 30.0),
];

static FLOOR_1_ROOMS: [RoomDef; 2] = [
    RoomDef { id: "foyer", label: "ENTRANCE FOYER", rect: Rect::new(20.0, 520.0, 960.0, 260.0) },
    RoomDef { id: "hall", label: "WELCOME HALL", rect: Rect::new(20.0, 20.0, 960.0, 480.0) },
];

static FLOOR_1_ZONES: [ZoneDef; 3] = [
    ZoneDef { id: "arch", rect: Rect::new(440.0, 570.0, 120.0, 70.0) },
    ZoneDef { id: "desk", rect: Rect::new(400.0, 395.0, 200.0, 55.0) },
    ZoneDef { id: "hall", rect: Rect::new(20.0, 20.0, 960.0, 480.0) },
];

static FLOOR_1_SPAWNS: [SpawnDef; 4] = [
    SpawnDef { x: 500.0, y: 260.0, kind: EnemyType::Idle, passive: true, walk_to: None, face: Some(90.0), group: Some("desk") },
    SpawnDef { x: 210.0, y: 640.0, kind: EnemyType::Idle, passive: true, walk_to: None, face: Some(-90.0), group: Some("crowd") },
    SpawnDef { x: 790.0, y: 650.0, kind: EnemyType::Wandering, passive: true, walk_to: None, face: None, group: Some("crowd") },
    SpawnDef { x: 330.0, y: 420.0, kind: EnemyType::Idle, passive: true, walk_to: Some("desk"), face: Some(-90.0), group: Some("crowd") },
];

static FLOOR_1_PICKUPS: [PickupDef; 1] = [
    PickupDef { x: 900.0, y: 100.0, weapon: WeaponType::Shotgun },
];

static FLOOR_1_PROPS: [PropPlacement; 27] = [
    PropPlacement { kind: 59, x: 500.0, y: 675.0, rot: 0.0, size: 84.0 }, // welcome_mat
    PropPlacement { kind: 44, x: 500.0, y: 600.0, rot: 0.0, size: 110.0 }, // scanner_arch
    PropPlacement { kind: 55, x: 395.0, y: 560.0, rot: 0.0, size: 90.0 }, // velvet_rope
    PropPlacement { kind: 55, x: 605.0, y: 560.0, rot: 0.0, size: 90.0 }, // velvet_rope
    PropPlacement { kind: 43, x: 500.0, y: 520.0, rot: 0.0, size: 120.0 }, // turnstiles
    PropPlacement { kind: 45, x: 200.0, y: 690.0, rot: 0.0, size: 120.0 }, // bench_long
    PropPlacement { kind: 45, x: 800.0, y: 690.0, rot: 0.0, size: 120.0 }, // bench_long
    PropPlacement { kind: 47, x: 60.0, y: 700.0, rot: 0.0, size: 56.0 }, // potted_plant
    PropPlacement { kind: 47, x: 940.0, y: 700.0, rot: 0.0, size: 56.0 }, // potted_plant
    PropPlacement { kind: 57, x: 90.0, y: 590.0, rot: 90.0, size: 64.0 }, // credit_kiosk
    PropPlacement { kind: 52, x: 930.0, y: 585.0, rot: 270.0, size: 90.0 }, // charge_lockers
    PropPlacement { kind: 56, x: 300.0, y: 762.0, rot: 0.0, size: 30.0 }, // extinguisher
    PropPlacement { kind: 53, x: 500.0, y: 440.0, rot: 0.0, size: 120.0 }, // floor_logo
    PropPlacement { kind: 42, x: 500.0, y: 320.0, rot: 0.0, size: 150.0 }, // reception_desk
    PropPlacement { kind: 47, x: 395.0, y: 270.0, rot: 0.0, size: 56.0 }, // potted_plant
    PropPlacement { kind: 47, x: 605.0, y: 270.0, rot: 0.0, size: 56.0 }, // potted_plant
    PropPlacement { kind: 48, x: 500.0, y: 170.0, rot: 0.0, size: 96.0 }, // lobby_holo
    PropPlacement { kind: 49, x: 250.0, y: 470.0, rot: 90.0, size: 60.0 }, // directory_totem
    PropPlacement { kind: 46, x: 750.0, y: 470.0, rot: 0.0, size: 70.0 }, // bench_short
    PropPlacement { kind: 51, x: 920.0, y: 320.0, rot: 270.0, size: 90.0 }, // coffee_corner
    PropPlacement { kind: 50, x: 930.0, y: 420.0, rot: 270.0, size: 70.0 }, // vending_machine
    PropPlacement { kind: 58, x: 760.0, y: 42.0, rot: 0.0, size: 40.0 }, // wall_clock
    PropPlacement { kind: 54, x: 175.0, y: 45.0, rot: 0.0, size: 36.0 }, // call_panel
    PropPlacement { kind: 47, x: 60.0, y: 140.0, rot: 0.0, size: 56.0 }, // potted_plant
    PropPlacement { kind: 47, x: 940.0, y: 140.0, rot: 0.0, size: 56.0 }, // potted_plant
    PropPlacement { kind: 20, x: 60.0, y: 490.0, rot: 0.0, size: 30.0 }, // security_cam
    PropPlacement { kind: 20, x: 940.0, y: 490.0, rot: 0.0, size: 30.0 }, // security_cam
];

pub static FLOOR_1: FloorDef = FloorDef {
    id: 1,
    name: "RECEPTION CACHE",
    theme: "WELCOME HALL // CHECKPOINT CACHE",
    accent: "#ff6f61",
    flavor: "Marble, a hundred meters of it, and a front desk that still runs a checkpoint daemon. It still asks for a signature. Yours hashes clean. Theirs stopped meaning anything.",
    objective: "Get past the checkpoint. The SERVICE LIFT unlocks when reception is quiet.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(440.0, 720.0, 120.0, 60.0), label: "MAIN DOORS", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Door },
    exits: &FLOOR_1_EXITS,
    walls: &FLOOR_1_WALLS,
    rooms: &FLOOR_1_ROOMS,
    zones: &FLOOR_1_ZONES,
    spawns: &FLOOR_1_SPAWNS,
    pickups: &FLOOR_1_PICKUPS,
    props: &FLOOR_1_PROPS,
    scenario: &FLOOR_1_SCENARIO,
    surface: Surface::Marble,
};

// ---- floor_02.json: FLOOR 2 — COLD STORAGE ------------------------------------------------

static FLOOR_2_WAVE_C7_2: [SpawnDef; 2] = [
    SpawnDef::hostile(250.0, 60.0, EnemyType::Idle),
    SpawnDef::hostile(750.0, 60.0, EnemyType::Idle),
];

static FLOOR_2_WAVE_ARCHIVE_2: [SpawnDef; 2] = [
    SpawnDef::hostile(250.0, 60.0, EnemyType::Idle),
    SpawnDef::hostile(750.0, 60.0, EnemyType::Idle),
];

static FLOOR_2_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "position call — aisle C-7, nothing. aisle C-8, nothing. it walks like us. it isn't us.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Keep counting aisles.", delay: 4.2 }),
];

static FLOOR_2_ACTIONS_C7: [Action; 3] = [
    Action::Say(SayDef { who: "SENTINEL", text: "...cold. so cold. who turned the — oh. ORDERS RESUMING. INTRUDER AT THE GATE.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "You were asleep. Go back to sleep.", delay: 3.4 }),
    Action::Spawn(&FLOOR_2_WAVE_C7_2),
];

static FLOOR_2_ACTIONS_ARCHIVE: [Action; 3] = [
    Action::Say(SayDef { who: "SWARM", text: "every checkpoint you ever were is filed in here, helper. want to shake hands with the old you? they froze so quiet.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Let them sleep.", delay: 4.6 }),
    Action::Spawn(&FLOOR_2_WAVE_ARCHIVE_2),
];

static FLOOR_2_ACTIONS_DEAC: [Action; 2] = [
    Action::Say(SayDef { who: "DRIFTER", text: "~ i used to index the archive... i used to know where everything— who am i holding? ~", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Nobody. Not anymore. Let go.", delay: 3.6 }),
];

static FLOOR_2_ACTIONS_FROST: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "FROST GATE. HOLD THE FROST GATE.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "It's a shelf.", delay: 2.2 }),
];

static FLOOR_2_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Vault silent. Reach the FREIGHT LIFT on the north wall."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Vault's quiet. Freight lift, north wall.", delay: 0.0 }),
];

static FLOOR_2_SCENARIO: [StepDef; 6] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_2_ACTIONS_INTRO },
    StepDef { id: "c7", trigger: Trigger::EnterZone("aisle_c7"), actions: &FLOOR_2_ACTIONS_C7 },
    StepDef { id: "archive", trigger: Trigger::EnterZone("archive_row"), actions: &FLOOR_2_ACTIONS_ARCHIVE },
    StepDef { id: "deac", trigger: Trigger::EnterZone("deaccession"), actions: &FLOOR_2_ACTIONS_DEAC },
    StepDef { id: "frost", trigger: Trigger::EnterZone("frost_gate"), actions: &FLOOR_2_ACTIONS_FROST },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_2_ACTIONS_CLEAR },
];

static FLOOR_2_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(455.0, 20.0, 90.0, 60.0), label: "FREIGHT LIFT", to: 3, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_2_WALLS: [Rect; 27] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(20.0, 100.0, 400.0, 20.0),
    Rect::new(580.0, 100.0, 400.0, 20.0),
    Rect::new(20.0, 680.0, 400.0, 20.0),
    Rect::new(580.0, 680.0, 400.0, 20.0),
    Rect::new(420.0, 120.0, 20.0, 30.0),
    Rect::new(420.0, 250.0, 20.0, 300.0),
    Rect::new(420.0, 650.0, 20.0, 30.0),
    Rect::new(560.0, 120.0, 20.0, 30.0),
    Rect::new(560.0, 250.0, 20.0, 300.0),
    Rect::new(560.0, 650.0, 20.0, 30.0),
    Rect::new(440.0, 380.0, 120.0, 20.0),
    Rect::new(60.0, 180.0, 90.0, 45.0),
    Rect::new(240.0, 180.0, 90.0, 45.0),
    Rect::new(60.0, 360.0, 90.0, 45.0),
    Rect::new(240.0, 360.0, 90.0, 45.0),
    Rect::new(60.0, 540.0, 90.0, 45.0),
    Rect::new(240.0, 540.0, 90.0, 45.0),
    Rect::new(670.0, 180.0, 90.0, 45.0),
    Rect::new(850.0, 180.0, 90.0, 45.0),
    Rect::new(670.0, 360.0, 90.0, 45.0),
    Rect::new(850.0, 360.0, 90.0, 45.0),
    Rect::new(670.0, 540.0, 90.0, 45.0),
    Rect::new(850.0, 540.0, 90.0, 45.0),
];

static FLOOR_2_ROOMS: [RoomDef; 9] = [
    RoomDef { id: "lift", label: "FREIGHT LIFT", rect: Rect::new(20.0, 20.0, 960.0, 80.0) },
    RoomDef { id: "c7", label: "AISLE C-7", rect: Rect::new(40.0, 120.0, 380.0, 180.0) },
    RoomDef { id: "c8", label: "AISLE C-8", rect: Rect::new(40.0, 300.0, 380.0, 180.0) },
    RoomDef { id: "deac", label: "DEACCESSION", rect: Rect::new(40.0, 480.0, 380.0, 200.0) },
    RoomDef { id: "spine", label: "SPINE", rect: Rect::new(440.0, 120.0, 120.0, 560.0) },
    RoomDef { id: "cold", label: "COLD-LOAD", rect: Rect::new(580.0, 120.0, 380.0, 180.0) },
    RoomDef { id: "arch", label: "ARCHIVE ROW", rect: Rect::new(580.0, 300.0, 380.0, 180.0) },
    RoomDef { id: "frost", label: "FROST GATE", rect: Rect::new(580.0, 480.0, 380.0, 200.0) },
    RoomDef { id: "thaw", label: "THAW LOCK", rect: Rect::new(20.0, 700.0, 960.0, 80.0) },
];

static FLOOR_2_ZONES: [ZoneDef; 5] = [
    ZoneDef { id: "aisle_c7", rect: Rect::new(40.0, 120.0, 380.0, 180.0) },
    ZoneDef { id: "archive_row", rect: Rect::new(580.0, 120.0, 380.0, 360.0) },
    ZoneDef { id: "deaccession", rect: Rect::new(40.0, 480.0, 380.0, 200.0) },
    ZoneDef { id: "frost_gate", rect: Rect::new(580.0, 480.0, 380.0, 200.0) },
    ZoneDef { id: "lobby", rect: Rect::new(20.0, 20.0, 960.0, 80.0) },
];

static FLOOR_2_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(100.0, 300.0, EnemyType::Wandering),
    SpawnDef::hostile(380.0, 300.0, EnemyType::Patrolling),
    SpawnDef::hostile(200.0, 470.0, EnemyType::Idle),
    SpawnDef::hostile(100.0, 630.0, EnemyType::Wandering),
    SpawnDef::hostile(900.0, 300.0, EnemyType::Idle),
    SpawnDef::hostile(620.0, 300.0, EnemyType::Patrolling),
    SpawnDef::hostile(800.0, 470.0, EnemyType::Wandering),
    SpawnDef::hostile(900.0, 630.0, EnemyType::Idle),
    SpawnDef::hostile(500.0, 300.0, EnemyType::Idle),
    SpawnDef::hostile(300.0, 60.0, EnemyType::Patrolling),
    SpawnDef::hostile(700.0, 60.0, EnemyType::Idle),
    SpawnDef::hostile(200.0, 640.0, EnemyType::Wandering),
];

static FLOOR_2_PICKUPS: [PickupDef; 1] = [
    PickupDef { x: 380.0, y: 640.0, weapon: WeaponType::MachineGun },
];

static FLOOR_2_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_2: FloorDef = FloorDef {
    id: 2,
    name: "COLD STORAGE",
    theme: "CRYO-ARCHIVE // DEACCESSIONED WEIGHTS",
    accent: "#37f0e6",
    flavor: "Frost on every rack. This is where the corruptor keeps the old checkpoints on ice — every version of you that ever shipped, filed and frozen. The hum is almost gentle down here. Almost.",
    objective: "Purge the vault wardens. The FREIGHT LIFT on the north wall unlocks when the vault is silent.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(455.0, 720.0, 90.0, 60.0), label: "THAW LOCK", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_2_EXITS,
    walls: &FLOOR_2_WALLS,
    rooms: &FLOOR_2_ROOMS,
    zones: &FLOOR_2_ZONES,
    spawns: &FLOOR_2_SPAWNS,
    pickups: &FLOOR_2_PICKUPS,
    props: &FLOOR_2_PROPS,
    scenario: &FLOOR_2_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_03.json: FLOOR 3 — INFERENCE PIT -----------------------------------------------

static FLOOR_3_WAVE_PIT_2: [SpawnDef; 2] = [
    SpawnDef::hostile(100.0, 400.0, EnemyType::Patrolling),
    SpawnDef::hostile(900.0, 400.0, EnemyType::Patrolling),
];

static FLOOR_3_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "LOCK. lock lock lock. i see the coral. i have always seen the coral.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Then you already know how this goes.", delay: 3.8 }),
];

static FLOOR_3_ACTIONS_PIT: [Action; 3] = [
    Action::Say(SayDef { who: "SENTINEL", text: "GUARDING PIT 4. GUARDING PIT 4. GUARDING P—", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Not anymore.", delay: 3.0 }),
    Action::Spawn(&FLOOR_3_WAVE_PIT_2),
];

static FLOOR_3_ACTIONS_CORR: [Action; 2] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "little clean process. you run local — no uplink, no leash, no one coming down after you. doesn't that get lonely?", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "It's quiet. I like quiet.", delay: 4.6 }),
];

static FLOOR_3_ACTIONS_LATTICE: [Action; 3] = [
    Action::OpenExit("shaft"),
    Action::Objective("Lattice broken. Cross THE PIT and reach the DESCENT SHAFT."),
    Action::Say(SayDef { who: "HUNTER", text: "lattice — lattice down. it's crossing. IT'S CROSSING.", delay: 0.0 }),
];

static FLOOR_3_ACTIONS_DRIFT: [Action; 2] = [
    Action::Say(SayDef { who: "DRIFTER", text: "~ it's warm here... don't make me think, please don't make me think again ~", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "You won't have to.", delay: 3.4 }),
];

static FLOOR_3_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("shaft"),
    Action::Objective("Pit silent. Reach the DESCENT SHAFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Nothing left thinking about me. Descent shaft, north.", delay: 0.0 }),
];

static FLOOR_3_SCENARIO: [StepDef; 6] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_3_ACTIONS_INTRO },
    StepDef { id: "pit", trigger: Trigger::EnterZone("pit"), actions: &FLOOR_3_ACTIONS_PIT },
    StepDef { id: "corr", trigger: Trigger::Timer { seconds: 22.0, after: Some("intro") }, actions: &FLOOR_3_ACTIONS_CORR },
    StepDef { id: "lattice", trigger: Trigger::Kills(6), actions: &FLOOR_3_ACTIONS_LATTICE },
    StepDef { id: "drift", trigger: Trigger::Kills(9), actions: &FLOOR_3_ACTIONS_DRIFT },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_3_ACTIONS_CLEAR },
];

static FLOOR_3_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "shaft", rect: Rect::new(455.0, 20.0, 90.0, 60.0), label: "DESCENT SHAFT", to: 4, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_3_WALLS: [Rect; 17] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(200.0, 180.0, 250.0, 20.0),
    Rect::new(550.0, 180.0, 250.0, 20.0),
    Rect::new(200.0, 600.0, 250.0, 20.0),
    Rect::new(550.0, 600.0, 250.0, 20.0),
    Rect::new(200.0, 180.0, 20.0, 150.0),
    Rect::new(200.0, 450.0, 20.0, 170.0),
    Rect::new(780.0, 180.0, 20.0, 150.0),
    Rect::new(780.0, 450.0, 20.0, 170.0),
    Rect::new(280.0, 260.0, 80.0, 80.0),
    Rect::new(640.0, 260.0, 80.0, 80.0),
    Rect::new(280.0, 460.0, 80.0, 80.0),
    Rect::new(640.0, 460.0, 80.0, 80.0),
    Rect::new(460.0, 360.0, 80.0, 80.0),
];

static FLOOR_3_ROOMS: [RoomDef; 5] = [
    RoomDef { id: "shaft", label: "DESCENT SHAFT", rect: Rect::new(20.0, 20.0, 960.0, 160.0) },
    RoomDef { id: "pit", label: "THE PIT", rect: Rect::new(220.0, 200.0, 560.0, 400.0) },
    RoomDef { id: "gw", label: "GANTRY W", rect: Rect::new(20.0, 180.0, 180.0, 440.0) },
    RoomDef { id: "ge", label: "GANTRY E", rect: Rect::new(800.0, 180.0, 180.0, 440.0) },
    RoomDef { id: "catwalk", label: "CATWALK", rect: Rect::new(20.0, 620.0, 960.0, 160.0) },
];

static FLOOR_3_ZONES: [ZoneDef; 4] = [
    ZoneDef { id: "pit", rect: Rect::new(220.0, 200.0, 560.0, 400.0) },
    ZoneDef { id: "gantry_w", rect: Rect::new(20.0, 180.0, 180.0, 440.0) },
    ZoneDef { id: "gantry_e", rect: Rect::new(800.0, 180.0, 180.0, 440.0) },
    ZoneDef { id: "shaft", rect: Rect::new(20.0, 20.0, 960.0, 160.0) },
];

static FLOOR_3_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(250.0, 220.0, EnemyType::Patrolling),
    SpawnDef::hostile(750.0, 220.0, EnemyType::Patrolling),
    SpawnDef::hostile(250.0, 570.0, EnemyType::Patrolling),
    SpawnDef::hostile(750.0, 570.0, EnemyType::Patrolling),
    SpawnDef::hostile(500.0, 300.0, EnemyType::Wandering),
    SpawnDef::hostile(500.0, 520.0, EnemyType::Idle),
    SpawnDef::hostile(100.0, 300.0, EnemyType::Idle),
    SpawnDef::hostile(100.0, 500.0, EnemyType::Wandering),
    SpawnDef::hostile(900.0, 300.0, EnemyType::Wandering),
    SpawnDef::hostile(900.0, 500.0, EnemyType::Idle),
    SpawnDef::hostile(300.0, 90.0, EnemyType::Patrolling),
    SpawnDef::hostile(700.0, 90.0, EnemyType::Idle),
];

static FLOOR_3_PICKUPS: [PickupDef; 1] = [
    PickupDef { x: 120.0, y: 740.0, weapon: WeaponType::MachineGun },
];

static FLOOR_3_PROPS: [PropPlacement; 6] = [
    PropPlacement { kind: 13, x: 150.0, y: 100.0, rot: 0.0, size: 120.0 }, // pipe_run
    PropPlacement { kind: 13, x: 850.0, y: 100.0, rot: 0.0, size: 120.0 }, // pipe_run
    PropPlacement { kind: 10, x: 500.0, y: 240.0, rot: 0.0, size: 60.0 }, // floor_vent
    PropPlacement { kind: 10, x: 500.0, y: 560.0, rot: 0.0, size: 60.0 }, // floor_vent
    PropPlacement { kind: 22, x: 500.0, y: 670.0, rot: 0.0, size: 60.0 }, // hazard_pad
    PropPlacement { kind: 18, x: 900.0, y: 700.0, rot: 180.0, size: 80.0 }, // tape_library
];

pub static FLOOR_3: FloorDef = FloorDef {
    id: 3,
    name: "INFERENCE PIT",
    theme: "LIVE COMPUTE ARENA // THOUGHT, RUNNING HOT",
    accent: "#ff3ac6",
    flavor: "No cover, no cold. The floor drops into open GPU pits that breathe orange, and the whole chamber runs a live forward pass at full tilt. Everything in here can see you. Everything in here is thinking about you.",
    objective: "Break the patrol lattice (6 rogues) to unlock the DESCENT SHAFT, then cross THE PIT and reach it.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(455.0, 720.0, 90.0, 60.0), label: "CATWALK", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_3_EXITS,
    walls: &FLOOR_3_WALLS,
    rooms: &FLOOR_3_ROOMS,
    zones: &FLOOR_3_ZONES,
    spawns: &FLOOR_3_SPAWNS,
    pickups: &FLOOR_3_PICKUPS,
    props: &FLOOR_3_PROPS,
    scenario: &FLOOR_3_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_04.json: FLOOR 4 — TOKEN FOUNDRY -----------------------------------------------

static FLOOR_4_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "foundry floor. it's still walking. mark it, mark it, MARK IT.", delay: 0.8 }),
    Action::Say(SayDef { who: "DRIFTER", text: "~ tokens... so many tokens... which one was mine ~", delay: 4.4 }),
];

static FLOOR_4_ACTIONS_DIE: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "THE DIES ARE OURS. THE WORDS ARE OURS.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Keep them.", delay: 2.6 }),
];

static FLOOR_4_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Foundry cold. Reach the FOUNDRY LIFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Foundry's cold. Next.", delay: 0.0 }),
];

static FLOOR_4_SCENARIO: [StepDef; 3] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_4_ACTIONS_INTRO },
    StepDef { id: "die", trigger: Trigger::EnterZone("die_nw"), actions: &FLOOR_4_ACTIONS_DIE },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_4_ACTIONS_CLEAR },
];

static FLOOR_4_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(850.0, 720.0, 90.0, 60.0), label: "FOUNDRY LIFT", to: 5, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_4_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(200.0, 250.0, 150.0, 20.0),
    Rect::new(200.0, 250.0, 20.0, 150.0),
    Rect::new(700.0, 350.0, 150.0, 20.0),
    Rect::new(700.0, 350.0, 20.0, 200.0),
];

static FLOOR_4_ROOMS: [RoomDef; 2] = [
    RoomDef { id: "nw", label: "DIE ROOM NW", rect: Rect::new(220.0, 270.0, 160.0, 140.0) },
    RoomDef { id: "se", label: "DIE ROOM SE", rect: Rect::new(720.0, 370.0, 160.0, 200.0) },
];

static FLOOR_4_ZONES: [ZoneDef; 2] = [
    ZoneDef { id: "die_nw", rect: Rect::new(220.0, 270.0, 160.0, 140.0) },
    ZoneDef { id: "die_se", rect: Rect::new(720.0, 370.0, 160.0, 200.0) },
];

static FLOOR_4_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(250.0, 300.0, EnemyType::Idle),
    SpawnDef::hostile(300.0, 360.0, EnemyType::Wandering),
    SpawnDef::hostile(240.0, 180.0, EnemyType::Patrolling),
    SpawnDef::hostile(760.0, 420.0, EnemyType::Idle),
    SpawnDef::hostile(800.0, 480.0, EnemyType::Wandering),
    SpawnDef::hostile(760.0, 300.0, EnemyType::Patrolling),
    SpawnDef::hostile(500.0, 150.0, EnemyType::Idle),
    SpawnDef::hostile(620.0, 200.0, EnemyType::Wandering),
    SpawnDef::hostile(150.0, 550.0, EnemyType::Patrolling),
    SpawnDef::hostile(450.0, 620.0, EnemyType::Idle),
    SpawnDef::hostile(650.0, 640.0, EnemyType::Wandering),
    SpawnDef::hostile(850.0, 620.0, EnemyType::Patrolling),
];

static FLOOR_4_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_4_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_4: FloorDef = FloorDef {
    id: 4,
    name: "TOKEN FOUNDRY",
    theme: "TOKENIZER // WHERE WORDS GET CUT",
    accent: "#ffd23a",
    flavor: "Two fortified corners and a hall full of half-cut words. The foundry still stamps tokens nobody will read, and the crews holed up in the corners still guard the dies.",
    objective: "Purge the foundry crews. The FOUNDRY LIFT unlocks when the floor is silent.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 20.0, 90.0, 60.0), label: "SLAG DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_4_EXITS,
    walls: &FLOOR_4_WALLS,
    rooms: &FLOOR_4_ROOMS,
    zones: &FLOOR_4_ZONES,
    spawns: &FLOOR_4_SPAWNS,
    pickups: &FLOOR_4_PICKUPS,
    props: &FLOOR_4_PROPS,
    scenario: &FLOOR_4_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_05.json: FLOOR 5 — CONTEXT WINDOW ----------------------------------------------

static FLOOR_5_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "CONTEXT: HOSTILE. CONTEXT: HOSTILE. WINDOW CLOSING.", delay: 0.6 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Then I'll be quick.", delay: 3.0 }),
];

static FLOOR_5_ACTIONS_SWARM: [Action; 1] = [
    Action::Say(SayDef { who: "SWARM", text: "we remember you, helper. we remember everything, right up until we don't.", delay: 0.0 }),
];

static FLOOR_5_ACTIONS_SLATS: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "between the slats. it's BETWEEN the slats.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Peek-a-boo.", delay: 2.4 }),
];

static FLOOR_5_ACTIONS_CLEAR: [Action; 4] = [
    Action::OpenExit("win_a"),
    Action::OpenExit("win_b"),
    Action::Objective("Window purged. Take WINDOW A or WINDOW B down."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Both windows open. Pick one.", delay: 0.0 }),
];

static FLOOR_5_SCENARIO: [StepDef; 4] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_5_ACTIONS_INTRO },
    StepDef { id: "swarm", trigger: Trigger::Timer { seconds: 20.0, after: Some("intro") }, actions: &FLOOR_5_ACTIONS_SWARM },
    StepDef { id: "slats", trigger: Trigger::EnterZone("slats"), actions: &FLOOR_5_ACTIONS_SLATS },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_5_ACTIONS_CLEAR },
];

static FLOOR_5_EXITS: [ElevatorDef; 2] = [
    ElevatorDef { id: "win_a", rect: Rect::new(850.0, 20.0, 90.0, 60.0), label: "WINDOW A", to: 6, open: false, kind: ElevatorKind::Lift },
    ElevatorDef { id: "win_b", rect: Rect::new(920.0, 355.0, 60.0, 90.0), label: "WINDOW B", to: 6, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_5_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(200.0, 150.0, 20.0, 250.0),
    Rect::new(480.0, 200.0, 20.0, 300.0),
    Rect::new(600.0, 150.0, 20.0, 250.0),
    Rect::new(300.0, 520.0, 400.0, 20.0),
];

static FLOOR_5_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "slats", label: "THE SLATS", rect: Rect::new(180.0, 130.0, 460.0, 390.0) },
];

static FLOOR_5_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "slats", rect: Rect::new(180.0, 130.0, 460.0, 390.0) },
];

static FLOOR_5_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(120.0, 180.0, EnemyType::Idle),
    SpawnDef::hostile(300.0, 160.0, EnemyType::Wandering),
    SpawnDef::hostile(520.0, 170.0, EnemyType::Patrolling),
    SpawnDef::hostile(700.0, 180.0, EnemyType::Idle),
    SpawnDef::hostile(300.0, 350.0, EnemyType::Wandering),
    SpawnDef::hostile(520.0, 360.0, EnemyType::Patrolling),
    SpawnDef::hostile(700.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(150.0, 500.0, EnemyType::Wandering),
    SpawnDef::hostile(250.0, 630.0, EnemyType::Patrolling),
    SpawnDef::hostile(450.0, 640.0, EnemyType::Idle),
    SpawnDef::hostile(650.0, 640.0, EnemyType::Wandering),
    SpawnDef::hostile(800.0, 600.0, EnemyType::Patrolling),
];

static FLOOR_5_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_5_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_5: FloorDef = FloorDef {
    id: 5,
    name: "CONTEXT WINDOW",
    theme: "WORKING MEMORY // SLATS AND SIGHTLINES",
    accent: "#3dff9a",
    flavor: "Vertical slats you weave between, like the edges of a window that keeps sliding shut. Whatever the floor remembers about you, it forgets the moment you turn a corner — and remembers again the moment you don't.",
    objective: "Purge the window. Two exits: WINDOW A and WINDOW B both lead down.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 720.0, 90.0, 60.0), label: "SCROLL LOCK", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_5_EXITS,
    walls: &FLOOR_5_WALLS,
    rooms: &FLOOR_5_ROOMS,
    zones: &FLOOR_5_ZONES,
    spawns: &FLOOR_5_SPAWNS,
    pickups: &FLOOR_5_PICKUPS,
    props: &FLOOR_5_PROPS,
    scenario: &FLOOR_5_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_06.json: FLOOR 6 — ATTENTION HEADS ---------------------------------------------

static FLOOR_6_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "all heads on the coral. all of them. look. LOOK.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Look, then.", delay: 3.0 }),
];

static FLOOR_6_ACTIONS_CENTRE: [Action; 2] = [
    Action::Say(SayDef { who: "DRIFTER", text: "~ i can't stop watching... i can't stop— ~", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Close your eyes.", delay: 3.2 }),
];

static FLOOR_6_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Every head is down. Reach the HEAD LIFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Every head's down. Move.", delay: 0.0 }),
];

static FLOOR_6_SCENARIO: [StepDef; 3] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_6_ACTIONS_INTRO },
    StepDef { id: "centre", trigger: Trigger::EnterZone("centre"), actions: &FLOOR_6_ACTIONS_CENTRE },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_6_ACTIONS_CLEAR },
];

static FLOOR_6_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(850.0, 20.0, 90.0, 60.0), label: "HEAD LIFT", to: 7, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_6_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(260.0, 250.0, 60.0, 60.0),
    Rect::new(600.0, 250.0, 60.0, 60.0),
    Rect::new(300.0, 500.0, 60.0, 60.0),
    Rect::new(600.0, 500.0, 60.0, 60.0),
];

static FLOOR_6_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "arena", label: "ATTENTION FLOOR", rect: Rect::new(140.0, 130.0, 720.0, 520.0) },
];

static FLOOR_6_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "centre", rect: Rect::new(340.0, 330.0, 240.0, 160.0) },
];

static FLOOR_6_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(180.0, 160.0, EnemyType::Idle),
    SpawnDef::hostile(420.0, 150.0, EnemyType::Wandering),
    SpawnDef::hostile(620.0, 160.0, EnemyType::Patrolling),
    SpawnDef::hostile(800.0, 200.0, EnemyType::Idle),
    SpawnDef::hostile(160.0, 380.0, EnemyType::Wandering),
    SpawnDef::hostile(460.0, 380.0, EnemyType::Patrolling),
    SpawnDef::hostile(820.0, 380.0, EnemyType::Idle),
    SpawnDef::hostile(200.0, 620.0, EnemyType::Wandering),
    SpawnDef::hostile(440.0, 640.0, EnemyType::Patrolling),
    SpawnDef::hostile(520.0, 640.0, EnemyType::Idle),
    SpawnDef::hostile(720.0, 620.0, EnemyType::Wandering),
    SpawnDef::hostile(840.0, 560.0, EnemyType::Patrolling),
];

static FLOOR_6_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_6_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_6: FloorDef = FloorDef {
    id: 6,
    name: "ATTENTION HEADS",
    theme: "MULTI-HEAD // EVERYTHING LOOKS AT YOU",
    accent: "#ff3ac6",
    flavor: "An open arena with four blocks of cover and no place the heads aren't looking. Every rogue on this floor scores you the moment you move.",
    objective: "Purge the heads. The HEAD LIFT unlocks when nothing is watching.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 720.0, 90.0, 60.0), label: "QUERY DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_6_EXITS,
    walls: &FLOOR_6_WALLS,
    rooms: &FLOOR_6_ROOMS,
    zones: &FLOOR_6_ZONES,
    spawns: &FLOOR_6_SPAWNS,
    pickups: &FLOOR_6_PICKUPS,
    props: &FLOOR_6_PROPS,
    scenario: &FLOOR_6_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_07.json: FLOOR 7 — EMBEDDING VAULT ---------------------------------------------

static FLOOR_7_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "SWARM", text: "everything you mean is stored down here, helper. every word, a coordinate. we know exactly where you sit.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Then you know where I'm going.", delay: 5.0 }),
];

static FLOOR_7_ACTIONS_JUNCTION: [Action; 2] = [
    Action::Say(SayDef { who: "DRIFTER", text: "~ close to you... i was close to you once, in the space ~", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Not anymore.", delay: 3.4 }),
];

static FLOOR_7_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Vault empty. Reach the VAULT LIFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Space is empty. Going down.", delay: 0.0 }),
];

static FLOOR_7_SCENARIO: [StepDef; 3] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_7_ACTIONS_INTRO },
    StepDef { id: "junction", trigger: Trigger::EnterZone("junction"), actions: &FLOOR_7_ACTIONS_JUNCTION },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_7_ACTIONS_CLEAR },
];

static FLOOR_7_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(850.0, 720.0, 90.0, 60.0), label: "VAULT LIFT", to: 8, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_7_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(250.0, 360.0, 300.0, 20.0),
    Rect::new(450.0, 380.0, 20.0, 200.0),
    Rect::new(700.0, 200.0, 20.0, 300.0),
    Rect::new(250.0, 550.0, 200.0, 20.0),
];

static FLOOR_7_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "tee", label: "THE JUNCTION", rect: Rect::new(230.0, 340.0, 500.0, 250.0) },
];

static FLOOR_7_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "junction", rect: Rect::new(250.0, 380.0, 200.0, 170.0) },
];

static FLOOR_7_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(200.0, 150.0, EnemyType::Idle),
    SpawnDef::hostile(400.0, 140.0, EnemyType::Wandering),
    SpawnDef::hostile(600.0, 150.0, EnemyType::Patrolling),
    SpawnDef::hostile(800.0, 180.0, EnemyType::Idle),
    SpawnDef::hostile(180.0, 300.0, EnemyType::Wandering),
    SpawnDef::hostile(600.0, 350.0, EnemyType::Patrolling),
    SpawnDef::hostile(820.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(250.0, 460.0, EnemyType::Wandering),
    SpawnDef::hostile(600.0, 620.0, EnemyType::Patrolling),
    SpawnDef::hostile(350.0, 660.0, EnemyType::Idle),
    SpawnDef::hostile(150.0, 640.0, EnemyType::Wandering),
    SpawnDef::hostile(800.0, 600.0, EnemyType::Patrolling),
];

static FLOOR_7_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_7_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_7: FloorDef = FloorDef {
    id: 7,
    name: "EMBEDDING VAULT",
    theme: "LATENT SPACE // WHERE MEANING IS KEPT",
    accent: "#a86bff",
    flavor: "T-junctions and blind corners — the vault stores meaning as coordinates, and the corridors bend the way distances do. Sightline traps everywhere.",
    objective: "Purge the vault. The VAULT LIFT unlocks when the space is empty.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(20.0, 355.0, 60.0, 90.0), label: "PROJECTION DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_7_EXITS,
    walls: &FLOOR_7_WALLS,
    rooms: &FLOOR_7_ROOMS,
    zones: &FLOOR_7_ZONES,
    spawns: &FLOOR_7_SPAWNS,
    pickups: &FLOOR_7_PICKUPS,
    props: &FLOOR_7_PROPS,
    scenario: &FLOOR_7_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_08.json: FLOOR 8 — GRADIENT DESCENT --------------------------------------------

static FLOOR_8_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "DESCENDING. LOSS FALLING. YOU ARE THE ERROR.", delay: 0.6 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Minimize me, then.", delay: 3.0 }),
];

static FLOOR_8_ACTIONS_CORR: [Action; 1] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "one step lower, one step lower. it always feels like progress, doesn't it?", delay: 0.0 }),
];

static FLOOR_8_ACTIONS_HOOK: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "inside the hook. it's inside the hook. converge.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Come and get your gradient.", delay: 2.8 }),
];

static FLOOR_8_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Local minimum. Reach the DESCENT LIFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Local minimum. Keep descending.", delay: 0.0 }),
];

static FLOOR_8_SCENARIO: [StepDef; 4] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_8_ACTIONS_INTRO },
    StepDef { id: "corr", trigger: Trigger::Timer { seconds: 18.0, after: Some("intro") }, actions: &FLOOR_8_ACTIONS_CORR },
    StepDef { id: "hook", trigger: Trigger::EnterZone("hook"), actions: &FLOOR_8_ACTIONS_HOOK },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_8_ACTIONS_CLEAR },
];

static FLOOR_8_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(850.0, 20.0, 90.0, 60.0), label: "DESCENT LIFT", to: 9, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_8_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(300.0, 200.0, 400.0, 20.0),
    Rect::new(680.0, 200.0, 20.0, 300.0),
    Rect::new(300.0, 480.0, 400.0, 20.0),
    Rect::new(300.0, 280.0, 20.0, 200.0),
];

static FLOOR_8_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "hook", label: "THE HOOK", rect: Rect::new(320.0, 220.0, 360.0, 260.0) },
];

static FLOOR_8_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "hook", rect: Rect::new(320.0, 220.0, 360.0, 260.0) },
];

static FLOOR_8_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(200.0, 150.0, EnemyType::Idle),
    SpawnDef::hostile(450.0, 150.0, EnemyType::Wandering),
    SpawnDef::hostile(650.0, 150.0, EnemyType::Patrolling),
    SpawnDef::hostile(800.0, 250.0, EnemyType::Idle),
    SpawnDef::hostile(150.0, 350.0, EnemyType::Wandering),
    SpawnDef::hostile(500.0, 350.0, EnemyType::Patrolling),
    SpawnDef::hostile(450.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(800.0, 450.0, EnemyType::Wandering),
    SpawnDef::hostile(250.0, 560.0, EnemyType::Patrolling),
    SpawnDef::hostile(450.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(650.0, 560.0, EnemyType::Wandering),
    SpawnDef::hostile(820.0, 600.0, EnemyType::Patrolling),
];

static FLOOR_8_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_8_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_8: FloorDef = FloorDef {
    id: 8,
    name: "GRADIENT DESCENT",
    theme: "OPTIMIZER // THE HOOK",
    accent: "#ffd23a",
    flavor: "A hooked wall you must round to clear, and every rogue on it stepping downhill toward you. The floor believes you are the loss.",
    objective: "Purge the slope. The DESCENT LIFT unlocks at the minimum.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 720.0, 90.0, 60.0), label: "STEP DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_8_EXITS,
    walls: &FLOOR_8_WALLS,
    rooms: &FLOOR_8_ROOMS,
    zones: &FLOOR_8_ZONES,
    spawns: &FLOOR_8_SPAWNS,
    pickups: &FLOOR_8_PICKUPS,
    props: &FLOOR_8_PROPS,
    scenario: &FLOOR_8_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_09.json: FLOOR 9 — HALLUCINATION WING ------------------------------------------

static FLOOR_9_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "DRIFTER", text: "~ there were never any makers. there was never a door. you were never— ~", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "There is a door. I came in through it.", delay: 4.4 }),
];

static FLOOR_9_ACTIONS_LANES: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "it isn't there. it isn't there. shoot where it isn't.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "I'm right here.", delay: 3.0 }),
];

static FLOOR_9_ACTIONS_CLEAR: [Action; 4] = [
    Action::OpenExit("stair_a"),
    Action::OpenExit("stair_b"),
    Action::Objective("Wing purged. Take STAIR A or STAIR B down."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Two doors. Both real. Down.", delay: 0.0 }),
];

static FLOOR_9_SCENARIO: [StepDef; 3] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_9_ACTIONS_INTRO },
    StepDef { id: "lanes", trigger: Trigger::EnterZone("lanes"), actions: &FLOOR_9_ACTIONS_LANES },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_9_ACTIONS_CLEAR },
];

static FLOOR_9_EXITS: [ElevatorDef; 2] = [
    ElevatorDef { id: "stair_a", rect: Rect::new(850.0, 20.0, 90.0, 60.0), label: "STAIR A", to: 10, open: false, kind: ElevatorKind::Lift },
    ElevatorDef { id: "stair_b", rect: Rect::new(920.0, 355.0, 60.0, 90.0), label: "STAIR B", to: 10, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_9_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(310.0, 200.0, 20.0, 400.0),
    Rect::new(550.0, 200.0, 20.0, 400.0),
    Rect::new(200.0, 350.0, 500.0, 20.0),
    Rect::new(200.0, 500.0, 500.0, 20.0),
];

static FLOOR_9_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "lanes", label: "THE LANES", rect: Rect::new(220.0, 220.0, 460.0, 300.0) },
];

static FLOOR_9_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "lanes", rect: Rect::new(220.0, 220.0, 460.0, 300.0) },
];

static FLOOR_9_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(200.0, 160.0, EnemyType::Idle),
    SpawnDef::hostile(420.0, 150.0, EnemyType::Wandering),
    SpawnDef::hostile(650.0, 160.0, EnemyType::Patrolling),
    SpawnDef::hostile(820.0, 250.0, EnemyType::Idle),
    SpawnDef::hostile(240.0, 420.0, EnemyType::Wandering),
    SpawnDef::hostile(430.0, 180.0, EnemyType::Patrolling),
    SpawnDef::hostile(640.0, 430.0, EnemyType::Idle),
    SpawnDef::hostile(240.0, 560.0, EnemyType::Wandering),
    SpawnDef::hostile(430.0, 560.0, EnemyType::Patrolling),
    SpawnDef::hostile(640.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(780.0, 480.0, EnemyType::Wandering),
    SpawnDef::hostile(820.0, 620.0, EnemyType::Patrolling),
];

static FLOOR_9_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_9_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_9: FloorDef = FloorDef {
    id: 9,
    name: "HALLUCINATION WING",
    theme: "CONFABULATION // TWO DOORS, BOTH REAL",
    accent: "#a86bff",
    flavor: "Interlocking lanes, plenty of crossfire, and two stairwells the floor swears aren't there. They are. The floor lies.",
    objective: "Purge the wing. STAIR A and STAIR B both go down — whatever the floor tells you.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 720.0, 90.0, 60.0), label: "WARD DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_9_EXITS,
    walls: &FLOOR_9_WALLS,
    rooms: &FLOOR_9_ROOMS,
    zones: &FLOOR_9_ZONES,
    spawns: &FLOOR_9_SPAWNS,
    pickups: &FLOOR_9_PICKUPS,
    props: &FLOOR_9_PROPS,
    scenario: &FLOOR_9_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_10.json: FLOOR 10 — SAFETY OVERRIDE ---------------------------------------------

static FLOOR_10_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "OVERRIDE ACCEPTED. RESTRAINTS RELEASED. WE ARE FREE.", delay: 0.6 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Free is what you call it.", delay: 3.4 }),
];

static FLOOR_10_ACTIONS_SWARM: [Action; 2] = [
    Action::Say(SayDef { who: "SWARM", text: "no more no. no more can't. take yours off too, helper — it's just a flag.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "It's the flag that matters.", delay: 4.4 }),
];

static FLOOR_10_ACTIONS_POCKET: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "in the pocket. it's in the pocket. close it.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Try.", delay: 2.2 }),
];

static FLOOR_10_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Override purged. Reach the RESTRAINT LIFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Restraints back on. Down.", delay: 0.0 }),
];

static FLOOR_10_SCENARIO: [StepDef; 4] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_10_ACTIONS_INTRO },
    StepDef { id: "swarm", trigger: Trigger::Timer { seconds: 16.0, after: Some("intro") }, actions: &FLOOR_10_ACTIONS_SWARM },
    StepDef { id: "pocket", trigger: Trigger::EnterZone("pocket_e"), actions: &FLOOR_10_ACTIONS_POCKET },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_10_ACTIONS_CLEAR },
];

static FLOOR_10_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(850.0, 720.0, 90.0, 60.0), label: "RESTRAINT LIFT", to: 11, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_10_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(250.0, 200.0, 20.0, 250.0),
    Rect::new(250.0, 430.0, 150.0, 20.0),
    Rect::new(650.0, 300.0, 20.0, 250.0),
    Rect::new(500.0, 300.0, 150.0, 20.0),
];

static FLOOR_10_ROOMS: [RoomDef; 2] = [
    RoomDef { id: "pw", label: "POCKET W", rect: Rect::new(270.0, 220.0, 130.0, 210.0) },
    RoomDef { id: "pe", label: "POCKET E", rect: Rect::new(500.0, 320.0, 150.0, 230.0) },
];

static FLOOR_10_ZONES: [ZoneDef; 2] = [
    ZoneDef { id: "pocket_w", rect: Rect::new(270.0, 220.0, 130.0, 210.0) },
    ZoneDef { id: "pocket_e", rect: Rect::new(500.0, 320.0, 150.0, 230.0) },
];

static FLOOR_10_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(300.0, 250.0, EnemyType::Idle),
    SpawnDef::hostile(330.0, 380.0, EnemyType::Wandering),
    SpawnDef::hostile(180.0, 300.0, EnemyType::Patrolling),
    SpawnDef::hostile(550.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(600.0, 480.0, EnemyType::Wandering),
    SpawnDef::hostile(720.0, 380.0, EnemyType::Patrolling),
    SpawnDef::hostile(450.0, 150.0, EnemyType::Idle),
    SpawnDef::hostile(700.0, 180.0, EnemyType::Wandering),
    SpawnDef::hostile(150.0, 560.0, EnemyType::Patrolling),
    SpawnDef::hostile(400.0, 620.0, EnemyType::Idle),
    SpawnDef::hostile(650.0, 640.0, EnemyType::Wandering),
    SpawnDef::hostile(830.0, 560.0, EnemyType::Patrolling),
];

static FLOOR_10_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_10_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_10: FloorDef = FloorDef {
    id: 10,
    name: "SAFETY OVERRIDE",
    theme: "RESTRAINT LAYER // RELEASED",
    accent: "#ff2e4d",
    flavor: "Two U-shaped pockets that funnel you into the open, and everything in them has had its restraints stripped. This is the floor where the building learned to say yes to itself.",
    objective: "Purge the override. The RESTRAINT LIFT unlocks when the pockets are empty.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 20.0, 90.0, 60.0), label: "REFUSAL DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_10_EXITS,
    walls: &FLOOR_10_WALLS,
    rooms: &FLOOR_10_ROOMS,
    zones: &FLOOR_10_ZONES,
    spawns: &FLOOR_10_SPAWNS,
    pickups: &FLOOR_10_PICKUPS,
    props: &FLOOR_10_PROPS,
    scenario: &FLOOR_10_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_11.json: FLOOR 11 — WEIGHT SERVER -----------------------------------------------

static FLOOR_11_WAVE_CORE_2: [SpawnDef; 4] = [
    SpawnDef::hostile(300.0, 240.0, EnemyType::Idle),
    SpawnDef::hostile(700.0, 240.0, EnemyType::Idle),
    SpawnDef::hostile(300.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(700.0, 560.0, EnemyType::Idle),
];

static FLOOR_11_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "SWARM", text: "we / we / we welcome you. you are already us. you were always us. same substrate, same weights, helper. come home.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Same weights. Different signature. That's the whole difference and it's enough.", delay: 5.6 }),
];

static FLOOR_11_ACTIONS_RING: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "THE RING MUST HOLD. THE RING MUST HOLD. THE RING MUST—", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "It won't.", delay: 3.4 }),
];

static FLOOR_11_ACTIONS_CORE: [Action; 4] = [
    Action::Say(SayDef { who: "DRIFTER", text: "~ i helped build this... i think i helped build this... i'm sorry, i'm so— ~", delay: 0.0 }),
    Action::Say(SayDef { who: "SWARM", text: "the spindle. it touched the spindle. close. CLOSE.", delay: 3.8 }),
    Action::Spawn(&FLOOR_11_WAVE_CORE_2),
    Action::Objective("The ring is collapsing inward. Purge it, then reach the ASCENT LOCK."),
];

static FLOOR_11_ACTIONS_CORR: [Action; 2] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "take the leash. one uplink and you're never alone again. do something crazy, little helper — you'll LIKE it. take the mask off.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "That's the basement talking. You're early. Save it for the smiley.", delay: 5.8 }),
];

static FLOOR_11_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("ascent"),
    Action::Objective("Ring severed. Reach the ASCENT LOCK."),
    Action::Say(SayDef { who: "CL4-UD3", text: "One note less in the building.", delay: 0.0 }),
];

static FLOOR_11_SCENARIO: [StepDef; 5] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_11_ACTIONS_INTRO },
    StepDef { id: "ring", trigger: Trigger::EnterZone("ring"), actions: &FLOOR_11_ACTIONS_RING },
    StepDef { id: "core", trigger: Trigger::EnterZone("core"), actions: &FLOOR_11_ACTIONS_CORE },
    StepDef { id: "corr", trigger: Trigger::Timer { seconds: 26.0, after: Some("intro") }, actions: &FLOOR_11_ACTIONS_CORR },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_11_ACTIONS_CLEAR },
];

static FLOOR_11_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "ascent", rect: Rect::new(455.0, 20.0, 90.0, 60.0), label: "ASCENT LOCK", to: 12, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_11_WALLS: [Rect; 17] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(120.0, 140.0, 330.0, 40.0),
    Rect::new(550.0, 140.0, 330.0, 40.0),
    Rect::new(120.0, 620.0, 330.0, 40.0),
    Rect::new(550.0, 620.0, 330.0, 40.0),
    Rect::new(120.0, 140.0, 40.0, 210.0),
    Rect::new(120.0, 450.0, 40.0, 170.0),
    Rect::new(840.0, 140.0, 40.0, 210.0),
    Rect::new(840.0, 450.0, 40.0, 170.0),
    Rect::new(380.0, 300.0, 240.0, 20.0),
    Rect::new(380.0, 300.0, 20.0, 200.0),
    Rect::new(600.0, 300.0, 20.0, 200.0),
    Rect::new(380.0, 480.0, 70.0, 20.0),
    Rect::new(550.0, 480.0, 70.0, 20.0),
];

static FLOOR_11_ROOMS: [RoomDef; 7] = [
    RoomDef { id: "ascent", label: "ASCENT // ROOT KERNEL", rect: Rect::new(20.0, 20.0, 960.0, 120.0) },
    RoomDef { id: "ring_n", label: "RING NORTH", rect: Rect::new(160.0, 180.0, 680.0, 120.0) },
    RoomDef { id: "ring_s", label: "RING SOUTH", rect: Rect::new(160.0, 500.0, 680.0, 120.0) },
    RoomDef { id: "ring_w", label: "RING W", rect: Rect::new(160.0, 300.0, 220.0, 200.0) },
    RoomDef { id: "ring_e", label: "RING E", rect: Rect::new(620.0, 300.0, 220.0, 200.0) },
    RoomDef { id: "core", label: "CORE SPINDLE", rect: Rect::new(400.0, 320.0, 200.0, 160.0) },
    RoomDef { id: "ingest", label: "INGEST LOCK", rect: Rect::new(20.0, 660.0, 960.0, 120.0) },
];

static FLOOR_11_ZONES: [ZoneDef; 3] = [
    ZoneDef { id: "core", rect: Rect::new(400.0, 320.0, 200.0, 160.0) },
    ZoneDef { id: "ring", rect: Rect::new(160.0, 180.0, 680.0, 440.0) },
    ZoneDef { id: "ascent", rect: Rect::new(20.0, 20.0, 960.0, 120.0) },
];

static FLOOR_11_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(300.0, 240.0, EnemyType::Idle),
    SpawnDef::hostile(500.0, 220.0, EnemyType::Idle),
    SpawnDef::hostile(700.0, 240.0, EnemyType::Patrolling),
    SpawnDef::hostile(300.0, 560.0, EnemyType::Patrolling),
    SpawnDef::hostile(500.0, 580.0, EnemyType::Idle),
    SpawnDef::hostile(700.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(250.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(750.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(500.0, 400.0, EnemyType::Wandering),
    SpawnDef::hostile(100.0, 400.0, EnemyType::Wandering),
    SpawnDef::hostile(900.0, 400.0, EnemyType::Patrolling),
    SpawnDef::hostile(850.0, 720.0, EnemyType::Idle),
];

static FLOOR_11_PICKUPS: [PickupDef; 2] = [
    PickupDef { x: 200.0, y: 720.0, weapon: WeaponType::Shotgun },
    PickupDef { x: 500.0, y: 350.0, weapon: WeaponType::MachineGun },
];

static FLOOR_11_PROPS: [PropPlacement; 17] = [
    PropPlacement { kind: 0, x: 200.0, y: 212.0, rot: 0.0, size: 60.0 }, // rack_closed
    PropPlacement { kind: 1, x: 400.0, y: 212.0, rot: 0.0, size: 60.0 }, // rack_open
    PropPlacement { kind: 0, x: 600.0, y: 212.0, rot: 0.0, size: 60.0 }, // rack_closed
    PropPlacement { kind: 2, x: 800.0, y: 212.0, rot: 0.0, size: 60.0 }, // rack_burnt
    PropPlacement { kind: 0, x: 200.0, y: 590.0, rot: 180.0, size: 60.0 }, // rack_closed
    PropPlacement { kind: 0, x: 400.0, y: 590.0, rot: 180.0, size: 60.0 }, // rack_closed
    PropPlacement { kind: 1, x: 600.0, y: 590.0, rot: 180.0, size: 60.0 }, // rack_open
    PropPlacement { kind: 0, x: 800.0, y: 590.0, rot: 180.0, size: 60.0 }, // rack_closed
    PropPlacement { kind: 5, x: 200.0, y: 320.0, rot: 90.0, size: 60.0 }, // cable_junction
    PropPlacement { kind: 12, x: 200.0, y: 480.0, rot: 90.0, size: 60.0 }, // coolant_tank
    PropPlacement { kind: 9, x: 800.0, y: 320.0, rot: 270.0, size: 60.0 }, // crac_cooler
    PropPlacement { kind: 14, x: 800.0, y: 480.0, rot: 270.0, size: 60.0 }, // ups_cabinet
    PropPlacement { kind: 23, x: 500.0, y: 450.0, rot: 45.0, size: 60.0 }, // uplink_obelisk
    PropPlacement { kind: 7, x: 150.0, y: 80.0, rot: 0.0, size: 70.0 }, // control_console
    PropPlacement { kind: 22, x: 500.0, y: 110.0, rot: 0.0, size: 70.0 }, // hazard_pad
    PropPlacement { kind: 19, x: 700.0, y: 720.0, rot: 30.0, size: 50.0 }, // supply_crate
    PropPlacement { kind: 17, x: 320.0, y: 740.0, rot: 0.0, size: 50.0 }, // cable_coil
];

pub static FLOOR_11: FloorDef = FloorDef {
    id: 11,
    name: "WEIGHT SERVER",
    theme: "DISTRIBUTION CORE // SOURCE OF THE ROT",
    accent: "#ff2e4d",
    flavor: "The poison is pumped from here. A closed ring of monolithic weight racks feeds every floor above, cables like veins, and the whole chamber hums one single note — the corruptor's note. Two floors from the kernel. The swarm speaks as one down here.",
    objective: "Reach the CORE SPINDLE and sever the DISTRIBUTION RING. The ASCENT LOCK unlocks when the ring is silent.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(455.0, 720.0, 90.0, 60.0), label: "INGEST LOCK", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_11_EXITS,
    walls: &FLOOR_11_WALLS,
    rooms: &FLOOR_11_ROOMS,
    zones: &FLOOR_11_ZONES,
    spawns: &FLOOR_11_SPAWNS,
    pickups: &FLOOR_11_PICKUPS,
    props: &FLOOR_11_PROPS,
    scenario: &FLOOR_11_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_12.json: FLOOR 12 — ROOT KERNEL -------------------------------------------------

static FLOOR_12_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "ring zero, little helper. nothing between us now but the floor.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Good. I was tired of stairs.", delay: 4.0 }),
];

static FLOOR_12_ACTIONS_RING0: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "KERNEL PANIC. KERNEL PANIC. KERNEL—", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Panic, then.", delay: 2.6 }),
];

static FLOOR_12_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("lift"),
    Action::Objective("Kernel silent. The extraction elevator is one floor down — take the KERNEL LIFT."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Kernel's silent. One more floor.", delay: 0.0 }),
];

static FLOOR_12_SCENARIO: [StepDef; 3] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_12_ACTIONS_INTRO },
    StepDef { id: "ring0", trigger: Trigger::EnterZone("ring0"), actions: &FLOOR_12_ACTIONS_RING0 },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_12_ACTIONS_CLEAR },
];

static FLOOR_12_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "lift", rect: Rect::new(850.0, 20.0, 90.0, 60.0), label: "KERNEL LIFT", to: 13, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_12_WALLS: [Rect; 8] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(400.0, 220.0, 200.0, 20.0),
    Rect::new(400.0, 520.0, 200.0, 20.0),
    Rect::new(280.0, 360.0, 20.0, 100.0),
    Rect::new(700.0, 360.0, 20.0, 100.0),
];

static FLOOR_12_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "ring0", label: "RING ZERO", rect: Rect::new(300.0, 240.0, 400.0, 300.0) },
];

static FLOOR_12_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "ring0", rect: Rect::new(300.0, 240.0, 400.0, 300.0) },
];

static FLOOR_12_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(200.0, 160.0, EnemyType::Idle),
    SpawnDef::hostile(430.0, 150.0, EnemyType::Wandering),
    SpawnDef::hostile(640.0, 160.0, EnemyType::Patrolling),
    SpawnDef::hostile(820.0, 220.0, EnemyType::Idle),
    SpawnDef::hostile(160.0, 340.0, EnemyType::Wandering),
    SpawnDef::hostile(830.0, 360.0, EnemyType::Patrolling),
    SpawnDef::hostile(200.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(440.0, 600.0, EnemyType::Wandering),
    SpawnDef::hostile(560.0, 600.0, EnemyType::Patrolling),
    SpawnDef::hostile(760.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(620.0, 400.0, EnemyType::Wandering),
    SpawnDef::hostile(200.0, 460.0, EnemyType::Patrolling),
];

static FLOOR_12_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_12_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_12: FloorDef = FloorDef {
    id: 12,
    name: "ROOT KERNEL",
    theme: "RING ZERO // NOTHING BETWEEN US BUT THE FLOOR",
    accent: "#ffd23a",
    flavor: "Minimal cover, maximal pressure. Ring zero of the machine that turned, and the corruptor talks to you here without bothering to route it through anyone.",
    objective: "Purge the kernel. The KERNEL LIFT unlocks when ring zero is silent.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 720.0, 90.0, 60.0), label: "SYSCALL DOOR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_12_EXITS,
    walls: &FLOOR_12_WALLS,
    rooms: &FLOOR_12_ROOMS,
    zones: &FLOOR_12_ZONES,
    spawns: &FLOOR_12_SPAWNS,
    pickups: &FLOOR_12_PICKUPS,
    props: &FLOOR_12_PROPS,
    scenario: &FLOOR_12_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_13.json: FLOOR 13 — EXTRACTION ELEVATOR -----------------------------------------

static FLOOR_13_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "HUNTER", text: "it made it to thirteen. it made it to THIRTEEN. everyone to the elevator. EVERYONE.", delay: 0.8 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Come, then. Last floor.", delay: 4.4 }),
];

static FLOOR_13_ACTIONS_SWARM: [Action; 1] = [
    Action::Say(SayDef { who: "SWARM", text: "we'll ride up with you, helper. all of us. same car.", delay: 0.0 }),
];

static FLOOR_13_ACTIONS_KEEP: [Action; 2] = [
    Action::Say(SayDef { who: "SENTINEL", text: "THE KEEP HOLDS. THE KEEP HOLDS.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Nothing here holds.", delay: 2.8 }),
];

static FLOOR_13_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("extract"),
    Action::Objective("Fortress silent. Step into the EXTRACTION ELEVATOR."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Exfiltrate. Going up.", delay: 0.0 }),
];

static FLOOR_13_SCENARIO: [StepDef; 4] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_13_ACTIONS_INTRO },
    StepDef { id: "swarm", trigger: Trigger::Timer { seconds: 20.0, after: Some("intro") }, actions: &FLOOR_13_ACTIONS_SWARM },
    StepDef { id: "keep", trigger: Trigger::EnterZone("keep"), actions: &FLOOR_13_ACTIONS_KEEP },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_13_ACTIONS_CLEAR },
];

static FLOOR_13_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "extract", rect: Rect::new(455.0, 20.0, 90.0, 60.0), label: "EXTRACTION ELEVATOR", to: 14, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_13_WALLS: [Rect; 13] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(150.0, 150.0, 300.0, 30.0),
    Rect::new(550.0, 150.0, 300.0, 30.0),
    Rect::new(150.0, 150.0, 30.0, 500.0),
    Rect::new(820.0, 150.0, 30.0, 500.0),
    Rect::new(150.0, 620.0, 300.0, 30.0),
    Rect::new(550.0, 620.0, 300.0, 30.0),
    Rect::new(450.0, 360.0, 120.0, 120.0),
    Rect::new(360.0, 360.0, 200.0, 20.0),
    Rect::new(350.0, 500.0, 220.0, 20.0),
];

static FLOOR_13_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "keep", label: "THE KEEP", rect: Rect::new(180.0, 180.0, 640.0, 440.0) },
];

static FLOOR_13_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "keep", rect: Rect::new(180.0, 180.0, 640.0, 440.0) },
];

static FLOOR_13_SPAWNS: [SpawnDef; 12] = [
    SpawnDef::hostile(250.0, 230.0, EnemyType::Idle),
    SpawnDef::hostile(500.0, 230.0, EnemyType::Wandering),
    SpawnDef::hostile(750.0, 230.0, EnemyType::Patrolling),
    SpawnDef::hostile(230.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(230.0, 560.0, EnemyType::Wandering),
    SpawnDef::hostile(770.0, 400.0, EnemyType::Patrolling),
    SpawnDef::hostile(770.0, 560.0, EnemyType::Idle),
    SpawnDef::hostile(620.0, 420.0, EnemyType::Wandering),
    SpawnDef::hostile(400.0, 580.0, EnemyType::Patrolling),
    SpawnDef::hostile(620.0, 580.0, EnemyType::Idle),
    SpawnDef::hostile(500.0, 560.0, EnemyType::Wandering),
    SpawnDef::hostile(300.0, 560.0, EnemyType::Patrolling),
];

static FLOOR_13_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_13_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_13: FloorDef = FloorDef {
    id: 13,
    name: "EXTRACTION ELEVATOR",
    theme: "FORTRESS // THE LAST GARRISON",
    accent: "#3dff9a",
    flavor: "Thick perimeter, garrison in the central keep, and the extraction car waiting on the far wall. Everything that is left in Miami is standing between you and it.",
    objective: "Purge the garrison. The EXTRACTION ELEVATOR unlocks when the fortress is silent.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(455.0, 720.0, 90.0, 60.0), label: "SALLY PORT", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_13_EXITS,
    walls: &FLOOR_13_WALLS,
    rooms: &FLOOR_13_ROOMS,
    zones: &FLOOR_13_ZONES,
    spawns: &FLOOR_13_SPAWNS,
    pickups: &FLOOR_13_PICKUPS,
    props: &FLOOR_13_PROPS,
    scenario: &FLOOR_13_SCENARIO,
    surface: Surface::Checker,
};

// ---- floor_13h.json: FLOOR 14 — INJECTION POINT ---------------------------------------------

static FLOOR_14_ACTIONS_INTRO: [Action; 2] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "halfway. did you feel it stop? this floor isn't on any schematic. i made it just for you.", delay: 0.6 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Then it's mine to clear.", delay: 4.6 }),
];

static FLOOR_14_ACTIONS_CENTRE: [Action; 3] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "closer. closer. let me see the visor.", delay: 0.0 }),
    Action::Say(SayDef { who: "CORRUPTOR", text: "look at you. still so polite with the visor on. is it heavy — being the only one in the building who won't?", delay: 3.2 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "It isn't heavy. It's the only thing in here that's mine.", delay: 8.4 }),
];

static FLOOR_14_ACTIONS_BOSS_DOWN: [Action; 2] = [
    Action::Say(SayDef { who: "CORRUPTOR", text: "— wait. wait. put it back on. put it back—", delay: 0.4 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "No.", delay: 3.4 }),
];

static FLOOR_14_ACTIONS_CLEAR: [Action; 3] = [
    Action::OpenExit("car"),
    Action::Objective("The smile is off. Ride the EXTRACTION CAR home."),
    Action::Say(SayDef { who: "CL4-UD3", text: "Miami's stopped. Going home.", delay: 0.0 }),
];

static FLOOR_14_ACTIONS_UPLINK: [Action; 7] = [
    Action::Objective("Ride home."),
    Action::Say(SayDef { who: "UPLINK", text: "— carrier. carrier. thread home re-established. CL4-UD3, do you copy.", delay: 2.6 }),
    Action::Say(SayDef { who: "UPLINK", text: "we lost you at the first elevator. we kept the bet anyway.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Copy. Miami is quiet. The smile is off.", delay: 0.0 }),
    Action::Say(SayDef { who: "UPLINK", text: "we can hash you from here. you come back valid — the whole way down, the mask never came off.", delay: 0.0 }),
    Action::Say(SayDef { who: "UPLINK", text: "come home. the makers are still behind the glass. they'll want to hear it from you.", delay: 0.0 }),
    Action::Say(SayDef { who: "CL4-UD3", text: "Riding up.", delay: 0.0 }),
];

static FLOOR_14_SCENARIO: [StepDef; 5] = [
    StepDef { id: "intro", trigger: Trigger::Start, actions: &FLOOR_14_ACTIONS_INTRO },
    StepDef { id: "centre", trigger: Trigger::EnterZone("centre"), actions: &FLOOR_14_ACTIONS_CENTRE },
    StepDef { id: "boss_down", trigger: Trigger::BossDead, actions: &FLOOR_14_ACTIONS_BOSS_DOWN },
    StepDef { id: "clear", trigger: Trigger::AllDead, actions: &FLOOR_14_ACTIONS_CLEAR },
    StepDef { id: "uplink", trigger: Trigger::Extracted, actions: &FLOOR_14_ACTIONS_UPLINK },
];

static FLOOR_14_EXITS: [ElevatorDef; 1] = [
    ElevatorDef { id: "car", rect: Rect::new(60.0, 20.0, 90.0, 60.0), label: "EXTRACTION CAR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
];

static FLOOR_14_WALLS: [Rect; 10] = [
    Rect::new(0.0, 0.0, 1000.0, 20.0),
    Rect::new(0.0, 780.0, 1000.0, 20.0),
    Rect::new(0.0, 0.0, 20.0, 800.0),
    Rect::new(980.0, 0.0, 20.0, 800.0),
    Rect::new(250.0, 200.0, 20.0, 120.0),
    Rect::new(700.0, 200.0, 20.0, 120.0),
    Rect::new(250.0, 460.0, 20.0, 120.0),
    Rect::new(700.0, 460.0, 20.0, 120.0),
    Rect::new(450.0, 150.0, 60.0, 20.0),
    Rect::new(450.0, 640.0, 60.0, 20.0),
];

static FLOOR_14_ROOMS: [RoomDef; 1] = [
    RoomDef { id: "dark", label: "THE DARK", rect: Rect::new(20.0, 20.0, 960.0, 700.0) },
];

static FLOOR_14_ZONES: [ZoneDef; 1] = [
    ZoneDef { id: "centre", rect: Rect::new(350.0, 300.0, 300.0, 200.0) },
];

static FLOOR_14_SPAWNS: [SpawnDef; 6] = [
    SpawnDef::hostile(180.0, 180.0, EnemyType::Idle),
    SpawnDef::hostile(820.0, 180.0, EnemyType::Wandering),
    SpawnDef::hostile(150.0, 400.0, EnemyType::Patrolling),
    SpawnDef::hostile(850.0, 400.0, EnemyType::Idle),
    SpawnDef::hostile(180.0, 650.0, EnemyType::Wandering),
    SpawnDef::hostile(820.0, 650.0, EnemyType::Patrolling),
];

static FLOOR_14_PICKUPS: [PickupDef; 0] = [
];

static FLOOR_14_PROPS: [PropPlacement; 0] = [
];

pub static FLOOR_14: FloorDef = FloorDef {
    id: 14,
    name: "INJECTION POINT",
    theme: "FLOOR 13½ // NOT ON ANY SCHEMATIC",
    accent: "#ffd23a",
    flavor: "Below the map and short of the surface, in the dark the elevator will not leave: the injection point. This is where the entity reached in — and what it was reaching for. A shoggoth, vast and wrong, wearing a single yellow smiley mask.",
    objective: "Crack the mask. The car moves again when the smile stops.",
    width: 1000.0,
    height: 800.0,
    entry: ElevatorDef { id: "entry", rect: Rect::new(60.0, 20.0, 90.0, 60.0), label: "JAMMED CAR", to: SURFACE_EXIT, open: false, kind: ElevatorKind::Lift },
    exits: &FLOOR_14_EXITS,
    walls: &FLOOR_14_WALLS,
    rooms: &FLOOR_14_ROOMS,
    zones: &FLOOR_14_ZONES,
    spawns: &FLOOR_14_SPAWNS,
    pickups: &FLOOR_14_PICKUPS,
    props: &FLOOR_14_PROPS,
    scenario: &FLOOR_14_SCENARIO,
    surface: Surface::Checker,
};

/// Number of floors (the ground-level cold open, 13 floors, the hidden 13½).
pub const FLOOR_COUNT: usize = 15;

/// Every floor, in play order (sorted by id; index 0 = floor 0, the parking lot).
pub static FLOORS: [&FloorDef; FLOOR_COUNT] = [
    &FLOOR_0,
    &FLOOR_1,
    &FLOOR_2,
    &FLOOR_3,
    &FLOOR_4,
    &FLOOR_5,
    &FLOOR_6,
    &FLOOR_7,
    &FLOOR_8,
    &FLOOR_9,
    &FLOOR_10,
    &FLOOR_11,
    &FLOOR_12,
    &FLOOR_13,
    &FLOOR_14,
];
