// @generated by tools/gen_props.py from props/props.json — DO NOT EDIT.
// Re-run `make gen-props` after editing the JSON (the ?viz PROPS page saves it).
//
// The saved pixel-art settings of the datacenter prop library: per prop the
// art-pixel size, per layer whether it is pixelated before or after its
// rotation. See docs/PROPS_FORMAT.md; the layers themselves live in
// src/props.rs (PROP_LAYERS).
#![allow(clippy::all)]

use crate::props::{LayerSetting, PixelMode, PropSettings, PROP_COUNT};

/// One entry per prop, in library order (index = prop id).
pub static PROP_SETTINGS: [PropSettings; PROP_COUNT] = [
    // 0 RACK / CLOSED
    PropSettings {
        kind: "rack_closed",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "fan a", pixel: PixelMode::After },
            LayerSetting { name: "fan b", pixel: PixelMode::After },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
        ],
    },
    // 1 RACK / OPEN
    PropSettings {
        kind: "rack_open",
        px: 1,
        layers: &[
            LayerSetting { name: "chassis", pixel: PixelMode::Before },
            LayerSetting { name: "fan", pixel: PixelMode::After },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
        ],
    },
    // 2 RACK / BURNT
    PropSettings {
        kind: "rack_burnt",
        px: 1,
        layers: &[
            LayerSetting { name: "lid", pixel: PixelMode::Before },
            LayerSetting { name: "hull", pixel: PixelMode::Before },
            LayerSetting { name: "sparks", pixel: PixelMode::After },
        ],
    },
    // 3 BLADE STACK
    PropSettings {
        kind: "blade_stack",
        px: 1,
        layers: &[
            LayerSetting { name: "enclosure", pixel: PixelMode::Before },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
        ],
    },
    // 4 CORE SWITCH
    PropSettings {
        kind: "core_switch",
        px: 1,
        layers: &[
            LayerSetting { name: "chassis", pixel: PixelMode::Before },
            LayerSetting { name: "ports", pixel: PixelMode::Before },
            LayerSetting { name: "cables", pixel: PixelMode::After },
        ],
    },
    // 5 CABLE JUNCTION
    PropSettings {
        kind: "cable_junction",
        px: 1,
        layers: &[
            LayerSetting { name: "boxes", pixel: PixelMode::Before },
            LayerSetting { name: "cables", pixel: PixelMode::After },
        ],
    },
    // 6 OPERATOR DESK
    PropSettings {
        kind: "operator_desk",
        px: 1,
        layers: &[
            LayerSetting { name: "desk", pixel: PixelMode::Before },
            LayerSetting { name: "paper a", pixel: PixelMode::Before },
            LayerSetting { name: "paper b", pixel: PixelMode::Before },
            LayerSetting { name: "mug", pixel: PixelMode::Before },
        ],
    },
    // 7 CONTROL CONSOLE
    PropSettings {
        kind: "control_console",
        px: 1,
        layers: &[
            LayerSetting { name: "shadow", pixel: PixelMode::Before },
            LayerSetting { name: "wing l", pixel: PixelMode::Before },
            LayerSetting { name: "wing r", pixel: PixelMode::Before },
            LayerSetting { name: "desk", pixel: PixelMode::Before },
            LayerSetting { name: "screen l", pixel: PixelMode::Before },
            LayerSetting { name: "screen c", pixel: PixelMode::Before },
            LayerSetting { name: "screen r", pixel: PixelMode::Before },
            LayerSetting { name: "chair", pixel: PixelMode::After },
        ],
    },
    // 8 HOLO TABLE
    PropSettings {
        kind: "holo_table",
        px: 1,
        layers: &[
            LayerSetting { name: "pedestal", pixel: PixelMode::Before },
            LayerSetting { name: "hologram", pixel: PixelMode::After },
        ],
    },
    // 9 CRAC COOLER
    PropSettings {
        kind: "crac_cooler",
        px: 1,
        layers: &[
            LayerSetting { name: "housing", pixel: PixelMode::Before },
            LayerSetting { name: "blower", pixel: PixelMode::After },
            LayerSetting { name: "led", pixel: PixelMode::Before },
        ],
    },
    // 10 FLOOR VENT
    PropSettings {
        kind: "floor_vent",
        px: 1,
        layers: &[
            LayerSetting { name: "grille", pixel: PixelMode::Before },
            LayerSetting { name: "airflow", pixel: PixelMode::After },
        ],
    },
    // 11 EXHAUST FAN
    PropSettings {
        kind: "exhaust_fan",
        px: 1,
        layers: &[
            LayerSetting { name: "duct", pixel: PixelMode::Before },
            LayerSetting { name: "blades", pixel: PixelMode::After },
            LayerSetting { name: "guard", pixel: PixelMode::Before },
        ],
    },
    // 12 COOLANT TANK
    PropSettings {
        kind: "coolant_tank",
        px: 1,
        layers: &[
            LayerSetting { name: "tank", pixel: PixelMode::Before },
            LayerSetting { name: "bubbles", pixel: PixelMode::After },
            LayerSetting { name: "hatch", pixel: PixelMode::Before },
        ],
    },
    // 13 PIPE RUN
    PropSettings {
        kind: "pipe_run",
        px: 1,
        layers: &[
            LayerSetting { name: "pipes", pixel: PixelMode::Before },
            LayerSetting { name: "valve", pixel: PixelMode::After },
        ],
    },
    // 14 UPS CABINET
    PropSettings {
        kind: "ups_cabinet",
        px: 1,
        layers: &[
            LayerSetting { name: "cabinet", pixel: PixelMode::Before },
            LayerSetting { name: "bolt", pixel: PixelMode::Before },
            LayerSetting { name: "charge", pixel: PixelMode::Before },
        ],
    },
    // 15 GENERATOR
    PropSettings {
        kind: "generator",
        px: 1,
        layers: &[
            LayerSetting { name: "block", pixel: PixelMode::Before },
            LayerSetting { name: "smoke", pixel: PixelMode::After },
            LayerSetting { name: "stack", pixel: PixelMode::Before },
            LayerSetting { name: "gauge", pixel: PixelMode::After },
        ],
    },
    // 16 CABLE TRAY
    PropSettings {
        kind: "cable_tray",
        px: 1,
        layers: &[
            LayerSetting { name: "tray", pixel: PixelMode::Before },
            LayerSetting { name: "cables", pixel: PixelMode::After },
        ],
    },
    // 17 CABLE COIL
    PropSettings {
        kind: "cable_coil",
        px: 1,
        layers: &[
            LayerSetting { name: "coil", pixel: PixelMode::Before },
            LayerSetting { name: "glints", pixel: PixelMode::After },
            LayerSetting { name: "lead", pixel: PixelMode::Before },
        ],
    },
    // 18 TAPE LIBRARY
    PropSettings {
        kind: "tape_library",
        px: 1,
        layers: &[
            LayerSetting { name: "chassis", pixel: PixelMode::Before },
            LayerSetting { name: "picker", pixel: PixelMode::After },
        ],
    },
    // 19 SUPPLY CRATE
    PropSettings {
        kind: "supply_crate",
        px: 1,
        layers: &[
            LayerSetting { name: "crate", pixel: PixelMode::Before },
            LayerSetting { name: "stencil", pixel: PixelMode::Before },
        ],
    },
    // 20 SECURITY CAM
    PropSettings {
        kind: "security_cam",
        px: 1,
        layers: &[
            LayerSetting { name: "mount", pixel: PixelMode::Before },
            LayerSetting { name: "cone", pixel: PixelMode::After },
            LayerSetting { name: "head", pixel: PixelMode::After },
        ],
    },
    // 21 FIRE SUPPRESSOR
    PropSettings {
        kind: "fire_suppressor",
        px: 1,
        layers: &[
            LayerSetting { name: "manifold", pixel: PixelMode::Before },
            LayerSetting { name: "tanks", pixel: PixelMode::Before },
            LayerSetting { name: "wheel l", pixel: PixelMode::After },
            LayerSetting { name: "wheel r", pixel: PixelMode::After },
            LayerSetting { name: "tag", pixel: PixelMode::Before },
        ],
    },
    // 22 HAZARD PAD
    PropSettings {
        kind: "hazard_pad",
        px: 1,
        layers: &[
            LayerSetting { name: "pad", pixel: PixelMode::Before },
            LayerSetting { name: "sign", pixel: PixelMode::Before },
        ],
    },
    // 23 UPLINK OBELISK
    PropSettings {
        kind: "uplink_obelisk",
        px: 1,
        layers: &[
            LayerSetting { name: "aura", pixel: PixelMode::After },
            LayerSetting { name: "shadow", pixel: PixelMode::Before },
            LayerSetting { name: "monolith", pixel: PixelMode::Before },
            LayerSetting { name: "seams", pixel: PixelMode::Before },
            LayerSetting { name: "escort", pixel: PixelMode::After },
        ],
    },
    // 24 CAR / POD
    PropSettings {
        kind: "car_pod",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "glass", pixel: PixelMode::Before },
            LayerSetting { name: "lidar", pixel: PixelMode::After },
            LayerSetting { name: "lights", pixel: PixelMode::Before },
        ],
    },
    // 25 CAR / SEDAN
    PropSettings {
        kind: "car_sedan",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "glass", pixel: PixelMode::Before },
            LayerSetting { name: "lidar", pixel: PixelMode::After },
            LayerSetting { name: "lights", pixel: PixelMode::Before },
        ],
    },
    // 26 CAR / OPEN
    PropSettings {
        kind: "car_open",
        px: 1,
        layers: &[
            LayerSetting { name: "spill", pixel: PixelMode::After },
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "door l", pixel: PixelMode::Before },
            LayerSetting { name: "door r", pixel: PixelMode::Before },
            LayerSetting { name: "cabin", pixel: PixelMode::Before },
            LayerSetting { name: "lidar", pixel: PixelMode::After },
            LayerSetting { name: "lights", pixel: PixelMode::Before },
        ],
    },
    // 27 DELIVERY VAN
    PropSettings {
        kind: "delivery_van",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "glass", pixel: PixelMode::Before },
            LayerSetting { name: "puck", pixel: PixelMode::After },
            LayerSetting { name: "lights", pixel: PixelMode::Before },
        ],
    },
    // 28 CHARGE PAD
    PropSettings {
        kind: "charge_pad",
        px: 1,
        layers: &[
            LayerSetting { name: "pad", pixel: PixelMode::Before },
            LayerSetting { name: "rings", pixel: PixelMode::After },
        ],
    },
    // 29 CAR / CHARGING
    PropSettings {
        kind: "car_charging",
        px: 1,
        layers: &[
            LayerSetting { name: "pad", pixel: PixelMode::Before },
            LayerSetting { name: "rings", pixel: PixelMode::After },
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "glass", pixel: PixelMode::Before },
            LayerSetting { name: "lidar", pixel: PixelMode::After },
            LayerSetting { name: "charge", pixel: PixelMode::Before },
        ],
    },
    // 30 MAIN GATE
    PropSettings {
        kind: "main_gate",
        px: 1,
        layers: &[
            LayerSetting { name: "lane", pixel: PixelMode::Before },
            LayerSetting { name: "posts", pixel: PixelMode::Before },
            LayerSetting { name: "scan", pixel: PixelMode::After },
            LayerSetting { name: "arm shadow", pixel: PixelMode::After },
            LayerSetting { name: "arm", pixel: PixelMode::After },
        ],
    },
    // 31 GUARD BOOTH
    PropSettings {
        kind: "guard_booth",
        px: 1,
        layers: &[
            LayerSetting { name: "wash", pixel: PixelMode::Before },
            LayerSetting { name: "booth", pixel: PixelMode::Before },
            LayerSetting { name: "ac fan", pixel: PixelMode::After },
            LayerSetting { name: "beacon", pixel: PixelMode::After },
        ],
    },
    // 32 BOLLARDS
    PropSettings {
        kind: "bollards",
        px: 1,
        layers: &[
            LayerSetting { name: "posts", pixel: PixelMode::Before },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
        ],
    },
    // 33 PLANTER
    PropSettings {
        kind: "planter",
        px: 1,
        layers: &[
            LayerSetting { name: "box", pixel: PixelMode::Before },
            LayerSetting { name: "shrub", pixel: PixelMode::After },
            LayerSetting { name: "lamp", pixel: PixelMode::Before },
        ],
    },
    // 34 LAMP POST
    PropSettings {
        kind: "lamp_post",
        px: 1,
        layers: &[
            LayerSetting { name: "pool", pixel: PixelMode::Before },
            LayerSetting { name: "shadow", pixel: PixelMode::Before },
            LayerSetting { name: "mast", pixel: PixelMode::Before },
            LayerSetting { name: "head", pixel: PixelMode::Before },
            LayerSetting { name: "moths", pixel: PixelMode::After },
        ],
    },
    // 35 EV BAY
    PropSettings {
        kind: "ev_bay",
        px: 1,
        layers: &[
            LayerSetting { name: "asphalt", pixel: PixelMode::Before },
            LayerSetting { name: "lines", pixel: PixelMode::Before },
            LayerSetting { name: "glyph", pixel: PixelMode::Before },
        ],
    },
    // 36 CROSSWALK
    PropSettings {
        kind: "crosswalk",
        px: 1,
        layers: &[
            LayerSetting { name: "asphalt", pixel: PixelMode::Before },
            LayerSetting { name: "stripes", pixel: PixelMode::Before },
        ],
    },
    // 37 DRONE PAD
    PropSettings {
        kind: "drone_pad",
        px: 1,
        layers: &[
            LayerSetting { name: "pad", pixel: PixelMode::Before },
            LayerSetting { name: "beacons", pixel: PixelMode::Before },
            LayerSetting { name: "drone", pixel: PixelMode::Before },
            LayerSetting { name: "rotor a", pixel: PixelMode::After },
            LayerSetting { name: "rotor b", pixel: PixelMode::After },
            LayerSetting { name: "rotor c", pixel: PixelMode::After },
            LayerSetting { name: "rotor d", pixel: PixelMode::After },
        ],
    },
    // 38 SCOOTER RACK
    PropSettings {
        kind: "scooter_rack",
        px: 1,
        layers: &[
            LayerSetting { name: "rail", pixel: PixelMode::Before },
            LayerSetting { name: "scooter a", pixel: PixelMode::Before },
            LayerSetting { name: "scooter b", pixel: PixelMode::Before },
            LayerSetting { name: "scooter c", pixel: PixelMode::Before },
        ],
    },
    // 39 DRAIN GRATE
    PropSettings {
        kind: "drain_grate",
        px: 1,
        layers: &[
            LayerSetting { name: "puddle", pixel: PixelMode::Before },
            LayerSetting { name: "grate", pixel: PixelMode::Before },
            LayerSetting { name: "sheen", pixel: PixelMode::After },
        ],
    },
    // 40 HOLO BILLBOARD
    PropSettings {
        kind: "holo_billboard",
        px: 1,
        layers: &[
            LayerSetting { name: "wash", pixel: PixelMode::After },
            LayerSetting { name: "shadow", pixel: PixelMode::Before },
            LayerSetting { name: "slab", pixel: PixelMode::Before },
            LayerSetting { name: "glyphs", pixel: PixelMode::After },
        ],
    },
    // 41 DUMPSTER
    PropSettings {
        kind: "dumpster",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "lid l", pixel: PixelMode::Before },
            LayerSetting { name: "lid r", pixel: PixelMode::Before },
            LayerSetting { name: "flies", pixel: PixelMode::After },
        ],
    },
    // 42 RECEPTION DESK
    PropSettings {
        kind: "reception_desk",
        px: 1,
        layers: &[
            LayerSetting { name: "shadow", pixel: PixelMode::Before },
            LayerSetting { name: "wing l", pixel: PixelMode::Before },
            LayerSetting { name: "wing r", pixel: PixelMode::Before },
            LayerSetting { name: "desk", pixel: PixelMode::Before },
            LayerSetting { name: "terminal", pixel: PixelMode::Before },
            LayerSetting { name: "chair", pixel: PixelMode::After },
        ],
    },
    // 43 TURNSTILES
    PropSettings {
        kind: "turnstiles",
        px: 1,
        layers: &[
            LayerSetting { name: "floor", pixel: PixelMode::Before },
            LayerSetting { name: "housings", pixel: PixelMode::Before },
            LayerSetting { name: "arm l", pixel: PixelMode::Before },
            LayerSetting { name: "arm r", pixel: PixelMode::After },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
        ],
    },
    // 44 SCANNER ARCH
    PropSettings {
        kind: "scanner_arch",
        px: 1,
        layers: &[
            LayerSetting { name: "mat", pixel: PixelMode::Before },
            LayerSetting { name: "arch", pixel: PixelMode::Before },
            LayerSetting { name: "sweep", pixel: PixelMode::After },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
        ],
    },
    // 45 BENCH / LONG
    PropSettings {
        kind: "bench_long",
        px: 1,
        layers: &[
            LayerSetting { name: "bench", pixel: PixelMode::Before },
            LayerSetting { name: "items", pixel: PixelMode::Before },
        ],
    },
    // 46 BENCH / SHORT
    PropSettings {
        kind: "bench_short",
        px: 1,
        layers: &[
            LayerSetting { name: "bench", pixel: PixelMode::Before },
            LayerSetting { name: "items", pixel: PixelMode::Before },
        ],
    },
    // 47 POTTED PLANT
    PropSettings {
        kind: "potted_plant",
        px: 1,
        layers: &[
            LayerSetting { name: "pot", pixel: PixelMode::Before },
            LayerSetting { name: "leaves", pixel: PixelMode::After },
            LayerSetting { name: "tag", pixel: PixelMode::Before },
        ],
    },
    // 48 LOBBY HOLO
    PropSettings {
        kind: "lobby_holo",
        px: 1,
        layers: &[
            LayerSetting { name: "wash", pixel: PixelMode::After },
            LayerSetting { name: "slab", pixel: PixelMode::Before },
            LayerSetting { name: "glyphs", pixel: PixelMode::After },
        ],
    },
    // 49 DIRECTORY TOTEM
    PropSettings {
        kind: "directory_totem",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "screen", pixel: PixelMode::After },
            LayerSetting { name: "wash", pixel: PixelMode::Before },
        ],
    },
    // 50 VENDING MACHINE
    PropSettings {
        kind: "vending_machine",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "front", pixel: PixelMode::Before },
            LayerSetting { name: "wash", pixel: PixelMode::Before },
        ],
    },
    // 51 COFFEE CORNER
    PropSettings {
        kind: "coffee_corner",
        px: 1,
        layers: &[
            LayerSetting { name: "counter", pixel: PixelMode::Before },
            LayerSetting { name: "machine", pixel: PixelMode::Before },
            LayerSetting { name: "cups", pixel: PixelMode::Before },
            LayerSetting { name: "steam", pixel: PixelMode::After },
        ],
    },
    // 52 CHARGE LOCKERS
    PropSettings {
        kind: "charge_lockers",
        px: 1,
        layers: &[
            LayerSetting { name: "cabinet", pixel: PixelMode::Before },
            LayerSetting { name: "leds", pixel: PixelMode::Before },
            LayerSetting { name: "cable", pixel: PixelMode::Before },
        ],
    },
    // 53 FLOOR LOGO
    PropSettings {
        kind: "floor_logo",
        px: 1,
        layers: &[
            LayerSetting { name: "inlay", pixel: PixelMode::Before },
            LayerSetting { name: "mark", pixel: PixelMode::Before },
            LayerSetting { name: "seams", pixel: PixelMode::Before },
        ],
    },
    // 54 CALL PANEL
    PropSettings {
        kind: "call_panel",
        px: 1,
        layers: &[
            LayerSetting { name: "wall", pixel: PixelMode::Before },
            LayerSetting { name: "panel", pixel: PixelMode::Before },
            LayerSetting { name: "arrows", pixel: PixelMode::Before },
        ],
    },
    // 55 VELVET ROPE
    PropSettings {
        kind: "velvet_rope",
        px: 1,
        layers: &[
            LayerSetting { name: "shadow", pixel: PixelMode::Before },
            LayerSetting { name: "rope", pixel: PixelMode::After },
            LayerSetting { name: "posts", pixel: PixelMode::Before },
        ],
    },
    // 56 EXTINGUISHER
    PropSettings {
        kind: "extinguisher",
        px: 1,
        layers: &[
            LayerSetting { name: "mount", pixel: PixelMode::Before },
            LayerSetting { name: "tank", pixel: PixelMode::Before },
            LayerSetting { name: "sign", pixel: PixelMode::Before },
        ],
    },
    // 57 CREDIT KIOSK
    PropSettings {
        kind: "credit_kiosk",
        px: 1,
        layers: &[
            LayerSetting { name: "body", pixel: PixelMode::Before },
            LayerSetting { name: "screen", pixel: PixelMode::After },
            LayerSetting { name: "wash", pixel: PixelMode::Before },
        ],
    },
    // 58 WALL CLOCK
    PropSettings {
        kind: "wall_clock",
        px: 1,
        layers: &[
            LayerSetting { name: "face", pixel: PixelMode::Before },
            LayerSetting { name: "hour", pixel: PixelMode::After },
            LayerSetting { name: "minute", pixel: PixelMode::After },
            LayerSetting { name: "second", pixel: PixelMode::After },
        ],
    },
    // 59 WELCOME MAT
    PropSettings {
        kind: "welcome_mat",
        px: 1,
        layers: &[
            LayerSetting { name: "mat", pixel: PixelMode::Before },
            LayerSetting { name: "pattern", pixel: PixelMode::Before },
        ],
    },
];
